### ISSUE TITLE
Add styled checkbox,radio button and switches

### ISSUE THREAD

**Issue by reza-irdev** [jgthms/bulma#1032]
Bulma is great. but it will be better to add styled check boxes, radios and switches in my opinion, because every OS has own style for these elements and this makes the appearance of the app not quite beautiful.

**Comment by jgthms** [comment]
Checkboxes and radios were styled in the first versions of Bulma but I dropped it because of the risk of breaking basic browser functionality.

Try https://github.com/hunzaboy/Cool-Checkboxes-for-Bulma.io

As for the switch, you can't make it draggable with CSS, so it's kind of dishonest to have it look like it is.
