### ISSUE TITLE
Css Tooltips.

### ISSUE THREAD

**Issue by mesqueeb** [jgthms/bulma#132]
Dear Bulma developers,
Sorry if this is not the correct location to post suggestions. I'm still quite new at github.

About tooltips, I previously suggested bootstrap-like tooltips, but someone told me you need JS for tooltips.
Now after some research I found beautiful pure CSS tooltips like these:
http://kazzkiq.github.io/balloon.css/
They work perfect on my browsers and my iPhone as well!

How about integrating something like this into Bulma?

Best regards,
-Luca Ban

**Comment by thebigmunch** [comment]
I don't see providing styling for a thing that requires JavaScript to put to use as a blocker if that thing is a common, useful component. Bulma already has styling for a hamburger menu, for example.

**Comment by ncksllvn** [comment]
Why not just include that as a separate dependency? I don't see the worth in adding this directly to Bulma.

**Comment by thebigmunch** [comment]
> Why not just include that as a separate dependency? I don't see the worth in adding this directly to Bulma.

Let me preface this by saying that I don't particularly care about tooltips being included as I don't use them very often.

But, your argument could be made for just about anything Bulma does. Again, Bulma already styles hamburger menus, but there are hamburger menus out there already. They're also something that requires JavaScript. Bulma does a grid, but there are grid frameworks out there so why have that in Bulma. And so on. There is also an argument for consistency of styling.

Your argument is not a valid one for whether something should be included. You didn't provide any specifics about why you think that way. If you were of the opinion that tooltips weren't useful or common enough for inclusion or you believed there would be too much effort required to add styling for them in Bulma, that'd make sense to bring up.  I may even agree with you. But something being available in another framework/package does not directly make it unworthy of being added.

I believe the way to go, if any, is to add styling for tooltip components and leave the implementation to users, which should be expected anyway.

**Comment by ncksllvn** [comment]
Great, then let me be more specific - you can justify hamburger menus and a grid system as being used often enough to warrant being directly in the framework. They are near necessities. Tooltips, not so much. Outside of that, I can think of a few reasons why tooltips don't belong in it:

- Tooltips aren't mobile friendly
- JS implementation for something like a hamburger menu is trivial; not not necessarily so with tooltips. The ones in the library being linked to are triggerable by hover-only. 
- Tooltips generally have minimal style. The ones in the library being linked to look nearly identical to Bootstrap's. I don't see the need to add it into the pipeline when there seems to be a near consensus on what tooltips should look like regardless of UI framework.
- Additional maintenance and bulk for a component that would be nearly exactly the same from an external dependency. 

Including Balloon.css in Bulma just because it would be more convenient that way rather than downloaded as a separate component is just silly. If we did this for every component someone decides they'd like in their project, we would have a monster of a UI framework rather than one kept lean.

**Comment by ncksllvn** [comment]
Also, I wasn't initially making argument. I was inquiring as to why you feel tooltips belong directly in the framework, hoping you could justify it before I really responded. But your response was pretty much "There's already a bunch of other components - why not this too?" and I don't think that holds water.

**Comment by mesqueeb** [comment]
Dear Ncksllvn,
(how do you pronounce your name?)

I often use tooltips when people click or tap or hover over an <input>. You see, I want to keep things simple, but like to give a bit more info when they are about to fill in an <input>. The good thing about tooltips with input is that they trigger when the user taps the input to start typing, even on mobile devices.

Another time I often use tooltips is with a blue info mark: If they hover over or tap on it on a mobile device they get an info balloon.

See the attached screenshots for my use cases:

![2016-03-23 11 05 03](https://cloud.githubusercontent.com/assets/3253920/13973589/a1fb6632-f0e7-11e5-870a-dc074140cffb.png)
![2016-03-23 11 06 47](https://cloud.githubusercontent.com/assets/3253920/13973590/a1fca2b8-f0e7-11e5-9021-ef4571f6a0f4.png)

To conclude:
I would say, it's definitely mobile friendly.
And I would just feel sad that Bulma has every element to create a basic website besides the tooltips.

But otherwise it's a great framework so far!

**Comment by ncksllvn** [comment]
I'm not saying there aren't use cases for tooltips, nor am I saying that they can't be mobile friendly. I'm saying that they aren't used enough to justify being in the framework and that there will definitely be issues with leaving the viewport on different devices, especially without a JS implementation.

**Comment by jgthms** [comment]
Some problems:

* can't put custom HTML in the tooltips
* it doesn't work on self-closing elements
* it uses pseudo content elements which can clash with Bulma ones
* you're gonna run into z-index issues
* tooltips are not a core design feature, but an enhancement

If you think Balloon.css is worth using, why not use it?

I could add some basic CSS tooltips but then I'd have to support it.

**Comment by alexgru** [comment]
Balloon SCSS for Bulma.io have [here >>>](https://github.com/alexgru/bulma-balloon.css)
