### ISSUE TITLE
Search for Bulma docs

### ISSUE THREAD

**Issue by ioan-cristea** [jgthms/bulma#1325]
Please add a search functionality for Bulma docs.

**Comment by dguo** [comment]
Algolia's free [DocSearch](https://community.algolia.com/docsearch/) is an option.

**Comment by gusmd** [comment]
I second this. I'm just starting out with Bulma (and web dev, for that matter), and looking through examples. Trying to find the specific classes and modifiers on the documentation right now is a pain. There are several options for adding searching to Jekyll-based docs.

**Comment by midzer** [comment]
As Jekyll is used for build tool, we could use https://github.com/christian-fei/Simple-Jekyll-Search to implement internal search functionality easily ourselves.

**Comment by patrickdaze** [comment]
I’ve done some testing with both [DocSearch](https://community.algolia.com/docsearch/) and [jekyll-algolia](https://community.algolia.com/jekyll-algolia/). I’m leaning towards DocSearch since it provide out-of-the-box functionality for scraping, indexing, and understanding the documentation’s hierarchy.

For example the following searches are able to display the section, and subsection of the documentation (examples are for testing purposes — please ignore the design aspect for now).

![dosearch-example](https://user-images.githubusercontent.com/250287/35160069-1b09df06-fd0a-11e7-836a-fef29366e7ee.png)

If we go forwards with DocSearch this is what I recommend:

1. [ ] Create the initial DocSearch configuration for testing (almost done, will update soon with link)
2. [ ] Create the initial frontend implementation for testing (almost done, will update soon with link)
3. [ ] Discuss, and adjust frontend design
4. [ ] Implement search versioning (possibly with http://versions.bulma.io/)
5. [ ] Update repo's documentation with search topic (if required)
6. [ ] Need site owners (Bulma team / @jgthms?) to [initialize conversation with Algolia](https://community.algolia.com/docsearch/)

Anyone agree, or disagree?

**Comment by patrickdaze** [comment]
The latest frontend code can be found on [my fork](https://github.com/patrickdaze/bulma/tree/feature-1325-search). For testing locally, [append this to your Jekyll configuration](https://github.com/patrickdaze/bulma/commit/b5363482ef7b71018bde2b0684a10cb3cf229afb#comments). Feel free to discuss, or do a PR on my repo if you have any design ideas.

![2018-01-23 22_04_47](https://user-images.githubusercontent.com/250287/35313495-a9a3d794-008e-11e8-8b2b-5d9727780faa.gif)

![screen shot 2018-01-23 at 10 06 08 pm](https://user-images.githubusercontent.com/250287/35313496-ad8f9398-008e-11e8-8fc7-19f3ddfd442e.png)

![screen shot 2018-01-23 at 10 06 33 pm](https://user-images.githubusercontent.com/250287/35313497-ada18c6a-008e-11e8-9850-9c630847f170.png)

**Comment by patrickdaze** [comment]
@jgthms (and Bulma team), are the changes proposed in this discussion headed in the right direction?

**Comment by techsin** [comment]
when will this be in production?

**Comment by Polcius** [comment]
That is amazing @patrickdaze ! Much needed feature, it is horrible to navigate through Bulma's docs webpage.

**Comment by Mortiferr** [comment]
Since website just got redesigned this might be a good time to look into this? 😉
I'm fairly new to Bulma and this is desperately missing feature especially with all the little stuff is hidden away such as the `has-text-centered` class I just spent 20 minutes looking for.

**Comment by k-j-kleist** [comment]
Personally, I found "The official Bulma book" very helpful (see the bottom of "https://bulma.io/documentation/").  Buying it is also a good opportunity to support Jeremy's work financially.

**Comment by adberard** [comment]
Why removing the search function ? It was there before. Removing the search function in a documentation website is madness.

**Comment by Mortiferr** [comment]
@adberard It can be pretty difficult to implement a search function that isn't absolute crap, so I think the priority was on getting a nicer and more functional website up, instead of search.

**Comment by san-kumar** [comment]
@patrickdaze is there a way to access that now? Any url where i can search the docs too. I mean until the official upgrades are done.. Thanks!

**Comment by mkstix6** [comment]
I love the style of the Bulma documentation site but I feel like a rearrangement or perhaps a removal of one level of subdivision would help with discovery if search is laborious to implement to satisfaction.

I feel like the two column grid layout with the icons for each section is nice to look at but not the quickest arrangement to scan.

In the beginning of using Bulma I couldn't find things quickly at all because of the various subdivisions.

Having spent more time with Bulma I often now know which page I'm trying to find but can't remember whether it's within, say, **Elements** or **Components**.
I head directly to **Layout** to look up the grid classes only to re-remember that **Columns** is its own sub-section.
I look for the responsive helpers in **Layout** or **Columns** but they're actually within **Modifiers**.

Of course, these are only my personal experiences and I'm probably carrying assumptions from previously using Zurb Foundation and Bootstrap.

I've always been a fan of Zurb Foundation's '[Kitchen Sink](https://foundation.zurb.com/sites/docs/kitchen-sink.html)' page although I'm sure it isn't to everybody's taste. For me I've found it makes it quick to search for things using simple `[cmd]+[F]` browser text find, a solid fallback when the search implementation itself is patchy in some situations. It allows me to rapidly scroll and stop when I glimpse something I need. Plus, scrolling past items helps micro-remind me of many things about the framework I would forget.

Thanks very much for all the hard work on Bulma!

**Comment by Maxhodges** [comment]
I agree with many others. I move around in the docs a lot the nested-levels and lack of search make it very inefficient to find what I'm looking for. We are using Algolia on [Vuetify](https://vuetifyjs.com/en/getting-started/quick-start) and it's brilliant

![image](https://user-images.githubusercontent.com/957271/53001131-48dc7d80-346d-11e9-83cb-d5d68ae8cb24.png)

Anything I could do to help accelerate this? This issue is coming up on its three year anniversary. If we did it for you, would you accept the PR, or are you against the idea for some reason? Maybe we could help sponsor it?

**Comment by patrickdaze** [comment]
@Maxhodges Is Vuetify is using DocSearch?

I created a pull request https://github.com/jgthms/bulma/pull/1622 a while back that uses DocSearch. It would need to be updated to match the new website structure, layout and style which I would gladly do. However the main issue is collaboration between the PR, Bulma team, and Algolia. See Launch Requirement checklist on the PR.

**Comment by Maxhodges** [comment]
@jgthms again, would it be worthwhile for us to put the work in on updating this PR, or are you simply not going to accept a search PR because you are philosophically against adding search?

**Comment by Maxhodges** [comment]
@patrickdaze I saw you PR and how the core maintainer ignored all pleas to even comment on it. What a shame. 

# Retweet all the [financial backers](https://bulma.io/backers/) for help?

https://twitter.com/max_hodges/status/1098264867167846400

https://twitter.com/max_hodges/status/1098265626710138881

https://twitter.com/max_hodges/status/1098266173177683968

**Comment by paulocastellano** [comment]
+1

**Comment by Maxhodges** [comment]
What do you guys think of building an alternative Bulma docs site? Clearly, the maintainer isn't making this a priority. He may control bulma.io, but we could get bulmaio.com or bulmadocs.com or something and deploy own unofficial docs site with Algolia. I'm a huge fan of Bulma but the structure of the docs and lack of search is pretty awful.

**Comment by patrickdaze** [comment]
Like the majority of projects, Bulma is open source but has a core contributor(s). Bulma takes suggestions, and in some cases implements them. However in the end they're the ones who own the project and can choose whether they want a feature.

Bulma is also in a space where it's open source (code MIT / website [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)) but the team also offers paid products, has ads, sponsors and paid backers. I think this is fine. Creators of great things have the right to be compensated. It can fuel changes and allow the product to evolve. 

Given these factors, open-source contributors can decide whether they want to contribute.

The team may or may not want search, however there could be alternatives to the current documentation site. The [DocSearch checklist](https://community.algolia.com/docsearch/who-can-apply.html):
- You must be the owner of the website, or at least have the power to update its content.
- Your website must be publicly available.
- Your website must be a documentation website.
- Your website must have some final content.

**Comment by sofiabsilva** [comment]
I'm shocked to see this is an issue from 2 years ago... I'm trying out Bulma for the first time and I'm finding the lack of a search very frustrating 👎 Should have been top priority when building the docs.

**Comment by CodeLuca** [comment]
We're working with Bulma now on a lot of our projects, and our consistent sole frustration is with the lack of search functionality within the documentation. Is there any potential timeline on this?

**Comment by Maxhodges** [comment]
i know. @jgthms replies instantly here:
https://github.com/jgthms/bulma/issues/2374

but can't bother to say a word on this issue. What a twat.

**Comment by patrickblackjr** [comment]
If @jgthms doesn't have time to maintain, maybe he could "hire" more core contributors that he trusts that could help manage the issues and PRs. There are a lot to manage for one person, perhaps that would help.

**Comment by Maxhodges** [comment]
if I put up a domain for an alternative docs site and get approval from Algolia for DocSearch, would any of you like to help put in the time to port over the docs into a new, search enabled format?

**Comment by patrickblackjr** [comment]
Idk, I'm not sure going around @jgthms is the best way to go about it.

**Comment by patrickblackjr** [comment]
There's a PR in, all he has to do is approve it. See #1622

**Comment by Maxhodges** [comment]
don't hold your breath!

**Comment by Sogl** [comment]
OMG, this issue is almost 2 years old
Tabs and nav categories without search is awful 🤦‍♂️ 
And I can't use Ctrl + F...

**Comment by benninkcorien** [comment]
I too came here looking for Search in the docs.

**Comment by neilime** [comment]
@jgthms is there any chance to have a search function in the near future ?

**Comment by sangeet** [comment]
Wow, I'm surprised that this isn't a thing yet. One question? Why? Search in any documentation is a must. Why should I have to guess where the heading styles, or the form styles, etc are? The categories are also deeply nested making looking through documentation a pain without the search.

Of course I can search in duckduckgo or something, but I just cannot understand that why hasn't this been implemented yet. Search is quite an essential feature of documentation, let alone of a documentation as nested as bulma's.

**Comment by Maxhodges** [comment]
above back in Feb I suggest we break away and build our own site. That's the only way you're gonna get search.

**Comment by thomasedwards** [comment]
I was trying to find this so I made one [https://bulmasearch.netlify.com](https://bulmasearch.netlify.com).

It’s rough around the edges but it works. PRs welcome!

**Comment by jremi** [comment]
@thomasedwards thank you sir! This is helpful.

**Comment by Alizadeh118** [comment]
I google this:
`site:https://bulma.io/documentation full height`

**Comment by RomainMazB** [comment]
Thanks to @thomasedwards .
@Alizadeh118 > I was using the same tricks but I'm an earth-friend :]

> One Google search is equal to turning on a 60W light bulb for 17 seconds

>Google says it spends about 0.0003 kWh of energy on an average search query, translating to roughly 0.2g of carbon dioxide. Related fact: searching the web 100 times is equivalent to drinking 1.5 tablespoons of orange juice, Google says. That’s hard work!

So I made a last search on Google to find a solution, which reached me here! As said by thomas it's not a perfect solution and is poorly not user-friendly but it seems to works.

Hope one day @patrickdaze solution will be implemented to official website!

**Comment by Maxhodges** [comment]
@RomainMazB  it's not roughly "0.2g carbon dioxide" if the source is solar and wind

https://sustainability.google/projects/announcement-100/

**Comment by Shipow** [comment]
Hello Bulma team, I'm working for Algolia and I'm super excited to see DocSearch on this docs!
Do you need any help to get this PR merged? Is there any issue I could help to solve with the index?
Let me know ^^

**Comment by thomasedwards** [comment]
Maybe fill out this form? 😄 https://community.algolia.com/docsearch/#join-docsearch-program

**Comment by Maxhodges** [comment]
@thomasedwards we've been down this road many times, but it's a dead end. @jgthms is relentlessly  ghosting this topic

**Comment by Fohlen** [comment]
I started out with `bulma` a while ago. It is an amazing framework. However the lack of a search function really drives me back to bootstrap. It is **really** annoying.

**Comment by patrickdaze** [comment]
As this thread has proven, the lack of search for the open source Bulma project is frustrating for the community. This is why @thomasedwards and myself (@patrickdaze) have been working on two projects.

The first is [Bulma Search](https://github.com/thomasedwards/bulmasearch). It provides indexing and and search through Algolia.

The second is [Search for Bulma : Chrome Extension](https://github.com/patrickdaze/bulma-search-chrome), a chrome extension that uses Bulma Search.

Both projects are not affiliated with nor developed by the core Bulma team. Feel free to send us PRs.

**Comment by Maxhodges** [comment]
in case it helps anyone else, we've switched from Bulma to https://tailwindcss.com/ for our projects. 
P.S. Tailwind docs include search tools!

**Comment by RomainMazB** [comment]
> in case it helps anyone else, we've switched from Bulma to https://tailwindcss.com/ for our projects.
> P.S. Tailwind docs include search tools!

Same here, but the fact that Bulma doesn't provide a search tool doesn't mean it's not a great framework.

TailwindCSS is different IMO, in such ways, it can't be compared to Bulma and can be more complicated for those who begin in web development.

<3 Bulma but for now, TailwindCSS took my heart ^^

**Comment by thomasedwards** [comment]
It’s Friday night, I’m trying to get everything done for the weekend. I want to center some text. I cannot find it. I’m done with this now, I’m switching to Tailwind.

**Comment by RomainMazB** [comment]
I've been to tailwind for a while now after tested Bulma and quit for the same reason, what's annoyed me first is for sure we can't search: it's a basic feature we can find anywhere else around the world but not there. But the fact this basic issue/feature request is open since more 2 years made telling myself: go away, the maintainers doesn't care about the developers feeling.

I've been noticed for every message you've wrote, I can't unsubscribe because I love to read jokes :D

**Comment by Maxhodges** [comment]
yeah at this point @jgthms essentially trolling you all. We switch to Tailwind.

**Comment by adelin-b** [comment]
Hey, im not using bulma for 2 years now but I still enjoy looking at this issues ! Here is a little script that I just did that enable a google search inside it !
https://openuserjs.org/scripts/adelin-b/Bulma_Search

**Comment by GMaiolo** [comment]
Why hasn't anything related to docs search been implemented in more than 2 years?

It's a major issue as far as I see, because it doesn't allow people to learn the framework in a comfortable way. I find myself google-guessing terms to get to the right place and it's extremely frustrating.

I just don't get it.

**Comment by svdHero** [comment]
Thank you @thomasedwards and @patrickdaze for your amazing work. Bulma Search is a lifesaver.
I am new to web front-end programming and cannot believe that this issue has been ignored by @jgthms for so long.
I hope this does not reflect the Bulma's overall maintenance philosophy.

**Comment by thomasedwards** [comment]
Welcome @svdHero – it’s now getting about 250 searches a day, so obviously in-demand! Hopefully won’t go over Algolia’s free community plan 😄

**Comment by thomasedwards** [comment]
:surprisedpikachuface:

**Comment by rafaelcdelgado** [comment]
> Personally, I found "The official Bulma book" very helpful (see the bottom of "https://bulma.io/documentation/"). Buying it is also a good opportunity to support Jeremy's work financially.

I Agree with the financial, but it's hard to find anyways...
