### ISSUE TITLE
Left alignment of navbar vs. other content in mobile

### ISSUE THREAD

**Issue by aphitiel** [jgthms/bulma#1347]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.0

### Description

On larger widths, the (top) navbar aligns with the other content. On mobile the navbars are further left than the other content.

Is this intended? Please see the attached screenshots. And thank you for BULMA!

Desktop:
![image](https://user-images.githubusercontent.com/5216257/31824405-32124668-b5af-11e7-9d4d-e3544c5b4b8d.png)

Mobile:
![image](https://user-images.githubusercontent.com/5216257/31824382-1bd37052-b5af-11e7-8c01-9aff4787ebc2.png)

**Comment by jgthms** [comment]
Yes it's intended to be this way.

On mobile, the left padding of the `navbar` is `1rem`: https://github.com/jgthms/bulma/blob/master/sass/components/navbar.sass

The left padding of the `section` is `1.5rem`: https://github.com/jgthms/bulma/blob/master/sass/layout/section.sass

The reason why it's aligned on desktop is because they're both in a `container`.
