### ISSUE TITLE
Question: How to make a sticky footer without using hacks

### ISSUE THREAD

**Issue by rafaelcn** [jgthms/bulma#1365]
Is there a way in Bulma to make a footer stick to the bottom of the page? If not, would be nice to have it on Bulma? I've been across this question before and I solve it by using one of the questions present on [stack overflow](https://stackoverflow.com/questions/3443606/make-footer-stick-to-bottom-of-page-correctly), however, the solution looks like a little hack to make a stick footer.

**Comment by jgthms** [comment]
Having a sticky footer in a CSS framework is tricky because the solution involves multiple elements.

One solution is to have the body in display flex in flex direction column, with two direct children only, the first one in flex grow 1.

But then several problems occur. You always need this column flexbox, which can behave weirdly if you’re not careful. You also always need these two direct children. You can’t add a third one.

Another option if the footer has a fixed height is to add a min height to its previous sibling, but that’s rarely an option.

Anyway, it’s not straightforward! I feel the solution will always be too restrictive to add to Bulma.

**Comment by rafaelcn** [comment]
So I'm stuck with one of those solutions, thanks for the clarification @jgthms! Making the previous sibling having its min-height would be an option on a project I'm working on. The trick though is to make the footer have a fixed height.

**Comment by begrafx** [comment]
> Having a sticky footer in a CSS framework is tricky because the solution involves multiple elements... 
> Anyway, it’s not straightforward! I feel the solution will always be too restrictive to add to Bulma.

With all due respect, why is this "not straightforward"? Bootstrap has such a thing, Tailwind has it. I don't understand why it would be any different/more difficult to do in Bulma.

**Comment by KhalilMouna** [comment]
For anyone looking, Bulma seems to have solved this with the [`fixed navbar`](https://bulma.io/2017/11/01/fixed-navbar/) functionality. Works pretty well!

**Comment by rafaelcn** [comment]
@KhalilMouna that's not the point of this issue.
