### ISSUE TITLE
need help in columns and responsiveness

### ISSUE THREAD

**Issue by 9Emi** [jgthms/bulma#1415]
This is about **Bulma | the Docs**.
 need help in columns and responsiveness

### Overview question 

look at this code 

<img alt="@9Emi" src="https://i.imgur.com/2OxvBpa.png" >

### Description of The question
it give me this !!
<img alt="@9Emi" src="https://i.imgur.com/CF0KhzL.png" >
4 columns in desktop view and i choose only 3 in one row and Second it must be 1 column
like this img 
<img alt="@9Emi" src="https://i.imgur.com/uCc3Kfv.png" >
How to fix this problem 
Sorry my English in not good :)

**Comment by jgthms** [comment]
`is-4-mobile` means the width of that column is `4 out of 12` or **one third**.

Since you have **four columns** here and since you're using `is-4` you end up with `16 out of 12` which is why there's not enough space for all your columns.

Check out the sizes docs: https://bulma.io/documentation/columns/sizes/

And you might want multiline as well: https://bulma.io/documentation/columns/options/#multiline

**Comment by 9Emi** [comment]
sorry it is not help :( And i love this framework ♥ , i understand all framework except this ..
for example in bootstrap `1 row = 12`  while Increase for example `14` the Increase  `2` go to next row
<img src="https://i.imgur.com/rGdXgPC.png" alt="ex" />
