### ISSUE TITLE
Lots of Bulma's extensions

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#1472]
Hi,

You can find a lot of Bulma's extensions:
- Accordion
- Checkradio
- Switch
- Calendar
- Carousel
- Timeline
- Steps
- iconPicker
- ...

on my site at the url https://wikiki.github.io

Sorry but updating extensions section of Bulma's documentation is not ideal for all those extensions (and displaying a picture is less convinient than a live demo).

Regards

**Comment by mhussa** [comment]
Your extensions are great and the new preview pages are too but I only found them by going to your github page.  All the current links to your components on the bulma extensions page are currently broken.  Can you replace them with just a single preview instead of one for each component? 

Thanks for sharing your work.

**Comment by Wikiki** [comment]
Thank you.
You're right, I forgot to update links in docs since I updated my page. I'll do that today.

**Comment by TheForgotten69** [comment]
Wonderful work thanks for sharing your work with us @Wikiki

**Comment by WG75** [comment]
Great work! thanks for sharing :)

**Comment by jgthms** [comment]
Website is up to date now!
