### ISSUE TITLE
Notification Close Button Location / CSS Bug

### ISSUE THREAD

**Issue by mbarwick83** [jgthms/bulma#1514]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

So I updated to the latest version of Bulma and noticed the close button on the notification style appears to be broken? Before there was some margin for the close/delete button. Now the button goes right to the top/right border.

I checked docs and noticed it's an "error" there as well. Is this on purpose?

See screenshot.

<img width="700" alt="screen shot 2017-12-08 at 1 48 54 pm" src="https://user-images.githubusercontent.com/330011/33780511-049a0b62-dc1f-11e7-8493-7f66ce51b28c.png">

**Comment by feute** [comment]
It has something to do with the usage of `em` instead of `rem`, I guess:

https://github.com/jgthms/bulma/blob/a99dede9082fdf2a7336fc0a64c068f2acad417b/sass/elements/notification.sass#L21-L24

Using `rem` adds the spacing correctly:

![2017-12-08-151622_581x235_scrot](https://user-images.githubusercontent.com/15493430/33781398-d9c17432-dc2a-11e7-917a-4231f0c2e589.png)
