### ISSUE TITLE
burger size is not responsive to navbar height

### ISSUE THREAD

**Issue by jimblue** [jgthms/bulma#1534]
**Overview of the problem**
This is about the Bulma CSS framework
I'm using Bulma version [0.6.1]

**Description**
Burger size is fixed. It's a problem when changing the navbar height for higher value as the burger will look too small.

**Expected behavior**
Changing the navbar height should have an influence on the burger size.

**Comment by raygervais** [comment]
@jimblue, @jgthms 
I agree entirely with the expected behavior here and would love to contribute toward a fix for this. I use this throughout quite a few projects and would love to have the burger size being responsive as one would expect.

**Comment by raygervais** [comment]
@jimblue, I interpreted the overall burger size as the button since it was an upgrade that I wanted as well. Was this correct, or did you mean the spacing in between the burger elements?

**Comment by jimblue** [comment]
@raygervais 
I mean the icon size inside the button. The button actually does resize responsively. But if it's kind of big the burger (3 lines / cross) will look too small.

It's because actually burger mixin define with of burger element in px.
Look the code here: https://github.com/jgthms/bulma/blob/fdeba5d111f8a7e695de4fc7a70966348daeeb03/sass/utilities/mixins.sass#L125

**Comment by jimblue** [comment]
In my opinion there is to solution, modify the mixin to make it responsive with rem value or by passing an argument to change it size.

**Comment by raygervais** [comment]
I see, agree that the 3 spans / lines need to be responsive as well. 
I suppose my interpretation derived from my experience of reducing the height of the navigation bar, and that causing issue with the hamburger menu. 

I believe the first solution you propose would be the correct fix.

If that is the case then I'd revert back my change since it is truly is already responsive and somehow I missed that. Then will look at the optimal algorithm for sizing. We could easily use the dimension itself which is passed in by the function signature:

https://github.com/jgthms/bulma/blob/fdeba5d111f8a7e695de4fc7a70966348daeeb03/sass/utilities/mixins.sass#L109

**Comment by jimblue** [comment]
Cool, so you have an idea how to modify the mixin to do so?

**Comment by raygervais** [comment]
Animation would have to be updated to accommodate the dynamic width of the spans, but this process wouldn't break the animation I imagine.

I imagine a dynamic calculation such as `calc($dimension - ($dimension / 2.5)) ` could do the trick for widths, since this also takes into account the margins. Note that 2.5 is just a hypothetical calculation, the value itself would be anywhere between 2.01 and n if my math is correct.

Animation width would take this into account in a similar fashion.

**Comment by jimblue** [comment]
Ok let's do it!! How can I help?

**Comment by raygervais** [comment]
@jimblue, 
Can you confirm this is the expected behavior? 

Default Height: 
![image](https://user-images.githubusercontent.com/14265337/34171455-5bd43a24-e4bc-11e7-82b3-8f8934b1688c.png)

Double Height, Still requires an update to the algorithm for the spacing of the hamburger 'layers'
![image](https://user-images.githubusercontent.com/14265337/34171498-7c93cf54-e4bc-11e7-9cfc-c1681d239fb3.png)

Half Width Burger Element: 
![image](https://user-images.githubusercontent.com/14265337/34171542-af9680f4-e4bc-11e7-8a46-077974fac4c0.png)
Double Width Burger Element: 
![image](https://user-images.githubusercontent.com/14265337/34171638-0af430c2-e4bd-11e7-9b39-704ff1c2845b.png)

As you can see, the idea that I'm proposing (still up for debate) is to make the width of the lines 40%, which was based on calculations I had done for the padding and margins which scale with the width. 
The height of the 'layers' would follow suit if you think this is the correct / desired functionality. Apologies if I've missed the mark on what you were expecting. 😃

**Comment by jimblue** [comment]
Hey @raygervais !

I see using percentage is kind working but it breaks the square ratio of the button which is not good.

Changing the navbar height already change the burger button to keep a square size.

That mean the 3 lines should use responsive value relative to the button size to not break the ratio.

What could be nice is also to space the 3 lines a bit more when the button get bigger.

In the end I think it would be probably better to define in px 3 sizes:
- is-normal (the actual default size)
- is-medium
- is- big

That way user could decide...

What do you think?

**Comment by raygervais** [comment]
Adding size modifier classes makes quite a bit of sense for a framework such as Bulma, it follows similar practice to other elements. The responsive classes may fix the issue which you and I mentioned. Currently, the square doesn't change on 0.6.1 when you change the height of the navbar, I am using the latest codebase. If it is supposed to, can you show even just via an image? 

Regarding these responsive classes, they me be the perfect class to utilize the percentage calculations, this way we can have a 16:9, 4:4, etc. I'll explore more of this when I have a chance today / tomorrow.

**Comment by jimblue** [comment]
I confirm that the square does change:

**default 3.25rem**
![3 25rem](https://user-images.githubusercontent.com/10623367/34182865-3eb2f0e6-e518-11e7-8d3c-9ec04d1e80a0.png)

**5rem**
![5rem](https://user-images.githubusercontent.com/10623367/34182869-444cb528-e518-11e7-8163-4d8e68c67d7d.png)

**7rem**
![7rem](https://user-images.githubusercontent.com/10623367/34182875-482fe4ee-e518-11e7-8cb3-33767b03d3a5.png)

**Comment by jimblue** [comment]
As I told you only the 3 lines / cross are not responsive...

**Comment by raygervais** [comment]
Interesting, I don't see the responsive change in my repository, perhaps I'm behind on a critical patch. Will revert any changes I've made, update the branch and apply the concepts we've discussed here. 

Do you believe these are appropriate class names?
- `is-bigger-burger` => Forces the widths to be 80% let's say of the overall size
- `is-default-burger` => Standard, widths appropriate to 16px in REM
- `is-smaller-burger` => Forces the widths to be 20% let's say of the overall size

**Comment by jimblue** [comment]
I think it would make more sens to use the following class on `.burger` element:

- is-small
- is-medium
- is-large

It's enough right?

Agree for the rest 😄

**Comment by raygervais** [comment]
Agreed 👍

**Comment by raygervais** [comment]
@jimblue, 
I disregarded is-medium since that is the default hamburger menu calculations, unless you can think of a good reason as to why, or I figured omitting `is-large` or `is-small` results in the defaults. `is-small` looks to be too close to the bottom, but I figured  I'd get your opinion on that first. Once we are done here, I'll update the PR with the spec.

Here are what the classes look like based on our agreed upon sizing conventions, with the included `is-active` to ensure the animation isn't broken: 

# is-large
![image](https://user-images.githubusercontent.com/14265337/34233881-c7d54ee4-e5b5-11e7-9dfb-2c3f0d5b35ff.png)

## is-active
![image](https://user-images.githubusercontent.com/14265337/34233861-ad13d53a-e5b5-11e7-8656-e5d54d6eaf3a.png)

# is-small
![image](https://user-images.githubusercontent.com/14265337/34233902-e00db618-e5b5-11e7-9028-95ec3854980f.png)

## is-active
![image](https://user-images.githubusercontent.com/14265337/34233912-ef3d9568-e5b5-11e7-942e-9ac872a5c8ba.png)

**Comment by jimblue** [comment]
Hey!!

Great job @raygervais ! 😄 

The small doesn't look too close the bottom IMO.

It's look like Bulma spirit is respected here, I think you can go for the PR !

**Comment by raygervais** [comment]
Thanks @jimblue, appreciate the help with figuring out the details here! 
I'll update the PR, and then get @jgthms to review for any issues / concerns. 
👍

**Comment by jimblue** [comment]
You're welcome, thanks to you for the PR

**Comment by devism** [comment]
This is desperately needed!

**Comment by raygervais** [comment]
@devism, see the [PR](https://github.com/jgthms/bulma/pull/1535) :)
