### ISSUE TITLE
Navbar text color changes on resizing the window

### ISSUE THREAD

**Issue by Cosbgn** [jgthms/bulma#1593]
A live pen here: https://codepen.io/anon/pen/jYYLwO

And a [.gif showing the problem](https://cl.ly/oiOS)

![screen recording 2018-01-08 at 01 22 pm](https://user-images.githubusercontent.com/17546283/34670708-c97def96-f477-11e7-9c7a-76f17b88ed8b.gif)

Why does it happen?

**Comment by ek1506** [comment]
To fix your problem, add the "has-text-white-bis" class to the navbar-item:
https://codepen.io/anon/pen/xpjWpQ

This problem occurred because you did not nest "navbar-start" and "navbar-end" under a "navbar-menu". The "navbar-menu" is hidden at smaller resolutions. Since you did not include it, the "navbar-start" remained visible with the default black color.
https://bulma.io/documentation/components/navbar/

**Comment by jgthms** [comment]
Thanks @ek1506.

**Comment by Cosbgn** [comment]
Thanks!
