### ISSUE TITLE
Difference between IE11 and Edge browser

### ISSUE THREAD

**Issue by focussing** [jgthms/bulma#1594]
IE11 shows this website completely different than for example Edge or Chrome.
I added screenshots of the site made on a Windows 10 virtual machine, with the same browser window size.

... any idea why?

www.pratenmetpim.nl

Edge:
![schermafbeelding 2018-01-10 om 17 27 56](https://user-images.githubusercontent.com/26736152/34783447-e55a2418-f62b-11e7-9184-47ad3b6f821a.png)

Internet Explorer 11:
![schermafbeelding 2018-01-10 om 17 27 49](https://user-images.githubusercontent.com/26736152/34783520-13569180-f62c-11e7-9efb-15159fd26eaa.png)

**Comment by danieldaeschle** [comment]
This is because Internet Explorer doesn't provide a full flex box support. Bulma also doesn't support internet explorer :(

**Comment by danieldaeschle** [comment]
i know how confusing it is.... many big companies and older people still use IE. But more and more frameworks doesn't provide support for IE.

**Comment by focussing** [comment]
Definitely true. In my case 99% of the schools use IE, and that the intended audience for my site...
However according to [this - scroll down completely](https://github.com/jgthms/bulma/issues/9) and [this](https://caniuse.com/#feat=flexbox) Bulma should support IE11.

It is bad that it is not clearly stated on the website which browsers support Bulma. Otherwise I would not even considered of using it.

**Comment by danieldaeschle** [comment]
maybe we should push this issue @jgthms

**Comment by focussing** [comment]
Would there be a solution for IE11 as well?

**Comment by emkajeej** [comment]
After looking at your site I can safely conclude the issues you're having are not Bulma related.
The dots aren't appearing because you use a shorthand notation for `background-size`. IE doesn't like this. Changing its value from `20px` to `20px 20px` fixes the issue.

The card cutoff is most likely because of the way you're using the columns; you are dividing a `.column.is-1` into even more columns, which in turn are containing a `.box'; their paddings are causing the smallest columns to overflow. To me the shown result is expected behaviour. To be honest I'm surprised it works so well in Chrome as it does.
I would fix it by getting rid of the `.is-half` classes on desktop, and changing the `.box` css from 
```css
padding: 1.25rem;
```
to
```css
width: 100%;
padding-top: 100%;
```
at least for the `.box` used in this particular case.

**Comment by jgthms** [comment]
Thanks for looking into this @emkajeej.
