### ISSUE TITLE
Maintain a stylus port

### ISSUE THREAD

**Issue by atilkan** [jgthms/bulma#1674]
I saw a couple of stylus port but they are not maintained. 
If you could merge a port to main repo i believe many people will help to maintain, me included.
Stylus is not hard to begin and maintain. Actually sass is already stylus with minor differences like variable declarations. 
Please consider.

**Comment by atilkan** [comment]
@VizuaaLOG you could write your reasons.

**Comment by jgthms** [comment]
Having stylus and sass combined in a single repo will confuse people, especially when looking through the source code and finding two occurrences of everything.

**Comment by atilkan** [comment]
@jgthms  I can say separate repo but you would write your reasons, nevermind.

**Comment by Log1x** [comment]
My fork, Bulma.styl is currently the most maintained fork but I do need to update it.

Feel free to do a PR :) Otherwise, I will get to it sometime this week. Work has been intense the past few weeks.

**Comment by atilkan** [comment]
@Log1x I saw your port. It wasn't updated to latest version. That why i created this issue. I will check it again. Thanks.

**Comment by Log1x** [comment]
If you want to push a PR with the update, I will accept it. It should only be about an hour or two of work. The hardest part is going through Bulma's commit history and finding commits that actually contain code changes as it's not always obvious. There's many circumstances where the commit message implies that there was only a small doc change, and then out of no where 20 lines will be changed on a random component.

**Comment by VizuaaLOG** [comment]
I vote against this because 1) it would mean two different source codes need to be updated for every new feature, while they're mostly the same there may be differences between stylus and sass. 2) a separate language in my opinion should be maintained by someone else, allowing the original repo manager to concentrate on what they are most comfortable with. Also as @jgthms said, having them both combined in the same repo would be confusing.

I suppose an organisation could be created for Bulma and the stylus repo could then be added to that with trusted community members being given access. Although this would depend on if @jgthms is comfortable doing this.

Also being separate repos what would stop them going in different directions?

**Comment by atilkan** [comment]
@Log1x Thanks. If i will dive it that means i also would change lots of things that i don't like. It would be something different according to my taste.

**Comment by Log1x** [comment]
If you're referring to the code style, feel free. It was adapted from a previous fork that went outdated for far too long with no intention to be maintained. I am not a fan either, but since I just import it into my projects and go from there, it's not really in sight.
