### ISSUE TITLE
Does bulma have a dropdown navigation menu?

### ISSUE THREAD

**Issue by JemiloII** [jgthms/bulma#172]
Was looking for the drop down navigation menu, but couldn't find it. Does this exist for bulma?

**Comment by jgthms** [comment]
Ah no it doesn't exist because it would require JavaScript. But if you just want to style it, try using a `.box`.

**Comment by JemiloII** [comment]
You don't need javascript at all. Take a look at this codepen. http://codepen.io/andornagy/pen/xhiJH

What do you think of an implementation like this?

**Comment by jgthms** [comment]
It's nice but requires a particular markup, and the styles of the header or tabs need to match, and it doesn't work on mobile.

I don't want to maintain something like this as well.

**Comment by JemiloII** [comment]
Alright

**Comment by jartaud** [comment]
@jgthms any example using .box?

**Comment by jaydeluca** [comment]
What about:

HTML:
```
<div class="nav-right nav-menu">
    <a class="nav-item" href="/">
        Home
    </a>
    <div class="has-dropdown">
        <a class="nav-item">
            <label>About</label>
        </a>
        <div class="dropdown box">
            <ul>
                <li><a>Policies</a></li>
                <li><a>Team</a></li>
            </ul>
        </div>
    </div>
</div>
```

CSS:
```
.dropdown {
  display: none;
  position: absolute;
  z-index: 9999;
}

.has-dropdown {
  &:hover {
    .dropdown {
      display: block;
    }
  }
}
```

**Comment by prograhammer** [comment]
@JemiloII That codepen could greatly benefit from `left: 100%;`:

```
/* Second, Third and more Tiers	*/
nav ul ul ul li {
	position: relative;
	top:-60px; 
	left:100%;
}
```
@jgthms I think that a menu like this would never be intended for mobile (you'd hide it and show a different menu on touch breakpoint). However, you would need JS to read the window size to make the submenus open left or right depending on remaining space. 

That being said, I still think menus like this are a little annoying because you have to play a hover game with your mouse and navigate down 3 levels without going outside the boundary or the menu collapses back. But it would be nice if perhaps there was something like the Bulma Menu inside each nav where you click and it expands downwards to more sublevels (instead of opening left/right). However this would be for the developer to do, not Bulma.
