### ISSUE TITLE
Navbar item with `has-dropdown` not aligning correctly

### ISSUE THREAD

**Issue by kajes** [jgthms/bulma#1728]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.6.2
My **browser** is: Chrome

### Description

A navbar-item with the has-dropdown class does not align properly vertically. Seem to be missing some property for padding.

### Expected behavior

Navbar-item with `has-dropdown` class should vertically align, just like regular navbar-items.

### Actual behavior

A navbar-item with the has-dropdown does not have proper vertical alignment. Removing the has-dropdown class centres the navbar-item just like regular navbar-items, but without padding.

Without `has-dropdown`:
![no-has-dropdown](https://user-images.githubusercontent.com/22004482/37383056-8783fc82-2746-11e8-96af-1dc22784bfa5.jpg)

With `has-dropdown`:
![has-dropdown](https://user-images.githubusercontent.com/22004482/37383058-879d4480-2746-11e8-8c1d-c525938379db.jpg)

**Comment by ek1506** [comment]
Hello, the ```navbar-item``` with ```has-dropdown``` still aligns properly. You can see an example here:
https://codepen.io/anon/pen/vRmdbZ

Since you didn't post your code I can't reproduce your issue exactly, but I suspect your dropdown isn't structured properly. Follow the [example in the docs](https://bulma.io/documentation/components/navbar/#dropdown-menu), which states the dropdown must have four elements:

- ```navbar-item``` with ```has-dropdown```, which contains two direct  children:
- ```navbar-link```
- ```navbar-dropdown``` element, which contains:
  - Instances of ```navbar-item``` and ```navbar-divider```

**Comment by kajes** [comment]
Yep, you're absolutely right. I figured out what was wrong, finally. Sorry 'bout that! Closing.
