### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by danieldaeschle** [jgthms/bulma#1746]
I create this issue because i think there is no progress at this repository.
Bulma is one of the biggest CSS frameworks on github and it is really easy to use and provide a good design.

But! it has a lot of things that can improved.
Some of the last changes was more than 2 month!

Why do you don't close issues or pull requests? We have a long way to release version 1....

Just tell me if i should believe in this project or just search another alternative...

**Comment by kigiri** [comment]
It clearly is still active

**Comment by stern-shawn** [comment]
https://opensource.stackexchange.com/questions/1753/whats-the-right-way-to-ask-if-a-github-project-is-maintained

The project had a release back on Jan 10 and the latest commit to master was 2 days ago. It's definitely still active! PRs may be slow to merge (heck, it took a good three months for one of mine to make it in) but there's nothing stopping you from making your own fork while you wait :)

**Comment by jgthms** [comment]
5 merged PRs and 32 issues closed in the last month. Is that negligible?

Also, a _ton_ of work has be done in the past 2 years. Bulma is at very stable state, where lots of bugs and improvement have made their way into the codebase, not including all the documentation that comes with it. All of this doesn't just go away!

You can't push bug fixes every week, because there's not that many anymore. And you can't push features every week either, otherwise Bulma would become bloated with unnecessary things that only satisfy a few and not the majority. You have to be careful!

It's easy to add a feature. It's very hard to maintain it!

Open source is difficult. I should know. Just be patient 😉

**Comment by danieldaeschle** [comment]
Ok, thanks :)
It was just a question because i wonder.
I really like it and i saw that it doesn't support internet explorer 11 which makes it not 100% useable for me.

It would be great if there were some fixes for IE11, just for the basic things.

I'm relative new to open source projects and i made my first PR on this repo.
