### ISSUE TITLE
Concerns about the naming conventions for the grid & responsive helpers.

### ISSUE THREAD

**Issue by ChaseGiunta** [jgthms/bulma#185]
Coming from Bootstrap, Flexboxgrid, etc. defining breakpoints by device (`is-mobile` `is-tablet`) feels unintuitive. Not only is something like `is-one-quarter-desktop` more cumbersome to type, but window widths don't equate to device types. I assume this is why those frameworks chose `xs`, `sm`, `md`, `lg` instead. The current Bulma naming could also potentially conflict when detecting devices for various other reasons (we currently, on another project, actually use `isMobile` as a class name for detecting **_touch_** screen devices for dealing with click events). These are just a couple reasons, but I think it may be beneficial for the grid classes to be agnostic in the long run.

Along those lines, I cannot think of a reason as to why classes such as `is-quarter`, `is-half`, etc. are necessary... Aren't they the equivalent to `is-3` & `is-6` or am I mistaken? Seems to add to the confusion.

With that that in mind, I'd hope to use the same naming conventions as some of these other popular frameworks (col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-2) for conciseness, familiarity, and to keep the breakpoints agnostic. Maybe these things could customized some way with Sass? 

Maybe I'm totally off-base here, but I figured I'd bring this up since Bulma is early & in Alpha. Thanks for the hard work @jgthms, loving Bulma so far!

**Comment by jbrooksuk** [comment]
I believe they're just helpers?

**Comment by jgthms** [comment]
Hi Chase

These are all fair points. Thanks for bringing them up. :+1: 

### Breakpoint suffixes

To be honest, I've alway been a bit confused with the `xs` `sm` `md` `lg` naming, because I could never remember in which order they were, and at what breakpoint they would be triggered.

If you look at the [responsive mixins](https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L73) you can see the same 4 breakpoints:

* `mobile` < 769px
* `tablet` between 769px and 980px
* `touch` which combines `mobile` and `tablet`
* `desktop` > 980px

(There's also `$widescreen` but not really used)

They're a bit opinionated I agree, but are a bit more readable.

### Shortcut names

About the `is-quarter` and `is-half`, yes they're equivalent to `is-3` and `is-6`. They're simply shortcuts, in a more human-readable format. I actually use `is-half` a lot, because it's easier to remember. I prefer leaving the option for both, it's not that much additional code.

I think having `is-half-mobile is-one-third-tablet is-one-quarter-desktop` is really readable.

### 

The same way that `is-half` and `is-6` co-exist, maybe I could include `xs` `sm` `md` and `lg` to co-exist with `mobile` `tablet` `desktop` and `widescreen`?

Customizing the class names with Sass is also an option. We could have additional variables like `$mobile: "mobile" !default` that you could define as `$mobile: "xs"`.

**Comment by tquetano-r7** [comment]
Speaking as a developer who has worked extensively with Bootstrap, the names that they give their classes (col-xs-6) is far less intuitive than is-half. Just because you have gotten comfortable with a bad system doesn't mean it's a good system. You think things like is-mobile and is-tablet is a "renaming" of *-xs and *-sm, but these provide greater context. What is `col-xs-3`? Looking at it through a non-bootstrap lens ... it says nothing about the actual CSS it provides. What about `columns is-mobile` and `column is-one-quarter`? That is far more descriptive.

@jgthms, keep doing you. I've been using Bootstrap for years, and it took all of 15 minutes to get on the bulma bandwagon.

**Comment by ChaseGiunta** [comment]
@tquetano-r7 

>You think things like is-mobile and is-tablet is a "renaming" of *-xs and *-sm, but these provide greater context. 

Yeah, I disagree. Just because my window is set to a smaller width doesn't mean I'm on a tablet, or a mobile device. It means my window is a smaller width. These are conflictual concerns.

I personally prefer `col-xs-3` because it's shorter, concise, and I clearly understand what's going on... `col-xs-3` = "_column is set to 3/12 on extra-small screen widths_". But hey, to each his own. These personal preferences could be solved with a sass option, or like @jgthms suggested, appending to the selectors.

More verbose naming? 
Pro:  Easier for framework beginners to understand what is going on, easily readable by everyone.
Con: More to type / no shorthand, lack of familiarity for some coming from frameworks like BS or others.

-----------

@jgthms appreciate the reply. I think either one of those solutions you mentioned would work great to address the concern. Totally understand the upside to readability, but myself (and I assume some others) may prefer the shorter options, again, for familiarity & brevity.

**Comment by jgthms** [comment]
I think having variables like `$mobile: "mobile" !default` that you could define as `$mobile: "xs"` is an option.

**Comment by lorvent** [comment]
@tquetano-r7 You may be correct, bootstrap may not be following good conventions.

but most of the people ( i guess) thinking to use bulma over bootstrap is because of flebox and tiny size,
so now if we need to learn a new syntax means...some people will prefer to stick with bootstrap to avoid learning curve (people already spending too much time learning js fws)

so my suggestion would be: create a doc mentioning how to customize class names while compiling so people can choose between bulma class names or bootstrap class names.

**Comment by jgthms** [comment]
Convention over configuration. 😉
