### ISSUE TITLE
[question] Bulma with Bootstrap

### ISSUE THREAD

**Issue by frogydiak** [jgthms/bulma#1865]
Not an issue but a question, I've been looking at documentation if there is a line that says "Can be use with Bootstrap" but found nothing. So, I am asking it here. 

I am thinking of using Bulma in Joomla which is using Bootstrap by default, can I use it side by side with Bootstrap? Will it have a conflict with styling?

Thanks!

**Comment by jdvivar** [comment]
The problem is your definition of `using`, it's too broad. If you want, you can load as many css frameworks as you want: Bootstrap, Foundation, Bulma, etc.

A css framework only makes sense when you use their classes. However classes of the same of course play better with themselves, because they were designed having that into account.

But of course, it's perfectly fine using Bulma and Bootstrap for different components, and even combine some of their classes.

However, I can't think of a single situation where THAT is actually needed. Chances are you probably are confused about what a css framework is. I recommend you to really understand why Bulma and Bootstrap were created, what problems they solve, how to use them, etc... and then asking yourself what sense would make using both at the same time.

I hope it helps!

**Comment by frogydiak** [comment]
I created a template in Joomla with my own CSS framework which I think Bulma is doing it so much better. So I am thinking of redoing my Joomla template using Bulma. Unfortunately, Joomla does not work properly without loading the default CSS framework which is bootstrap. So, I will be forced to have to use Bootstrap in a way.

If you are asking, why do I want to use Bulma on top of Bootstrap then, why not just use Bootstrap? It is because the Joomla bootstrap version is 2.3.2, old and not as cool as Bulma. If I use the latest version of Boostrap, it will or might conflict with the older version which cannot be disabled to use the latest version. It is not that I choose to  use both, I  don't have a choice :D but to use both.

But thank you for answering my question that it can co-exists.

**Comment by jgthms** [comment]
Yeah they _can_ co-exist. But you'll have differences with:

* reset: Bootstrap uses normalize, Bulma uses minireset
* global styles: like `body`, `html`, `a`…
* classes with the same name

There's probably a way to use Joomla without Bootstrap, I'm sure. Otherwise, use WordPress 😉
