### ISSUE TITLE
The difference between Navbar and Header

### ISSUE THREAD

**Issue by tsanyqudsi** [jgthms/bulma#189]
I'm a bit confused, in your documentation navbar is pretty much a container consisting navigation items while lack of mobile support ( such as the hamburger menu ) while header has the hamburger menu and apparently have a lot of items there.

**Comment by jgthms** [comment]
Yeah the name `navbar` is not perfect. It's basically a container to have things vertically aligned, with one element on the left, one on the right. I was thinking of calling it something else, like simply `bar` or `shelf`.

The `header` could be called `navbar` or `nav` instead, because it's mostly a navigation component.

I'm open to suggestions.

**Comment by tsanyqudsi** [comment]
i do suggest that we add the hamburger menu for the `navbar` and the `header `should be the hero :smiley: 

we can move the `navbar `and add it to the layout menu along the other layouts ( and also merging `container `into `header`,`section`, and `footer`. So it's going to be : 

Nav Header Section Footer

This way you don't have to add `container `class everytime

**Comment by jgthms** [comment]
The container class is still needed though. I don't understand why you want to get rid of it.

**Comment by jgthms** [comment]
There is now only `nav`: http://bulma.io/documentation/components/nav/
