### ISSUE TITLE
segmentation fault hero.sass

### ISSUE THREAD

**Issue by osixia** [jgthms/bulma#191]
Hi thanks for this great tool !

I use Bulma v0.0.24 and I get a segmentation fault from gulp-sass compiler, 
the file hero.sass seems to be the probleme.

I'm not familiar with sass so i tried to convert it to scss and it failed. Other files are fine.

The problems seems to come from the each loop but i don't know mutch...
do you have any solution ?

Thanks

**Comment by jgthms** [comment]
I have no idea what a segmentation problem is.

Can you share the full error message?

**Comment by lNbdy** [comment]
Yeah, I am also having a segfault but it doesn't show any error.

After some investigation, I think this has something to do with Node-Sass. All I could find about this problem was this article: 

https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9#.wyz74h9bp

The interesting part is the last one:

> If your code does not compile with the Sass compiler, it is broken, and will eventually break in LibSass and Node Sass without warning.

Your code looks good to me though...

**Comment by 3noch** [comment]
@jgthms You know programming has progressed when...people no longer recognize the term "segmentation fault." 😜

**Comment by lNbdy** [comment]
Alright, the problem comes from the :not selector inside the sass/layout/hero.sass file, at line 74 

`.header-item > a:not(.button)`

**Comment by lNbdy** [comment]
https://github.com/sass/libsass/pull/2032

Updating node-sass to 3.6.0 (and libsass) fixes the problem. Thanks!

**Comment by osixia** [comment]
indeed it fixes the problem :)
thanks !
