### ISSUE TITLE
$navbar-box-shadow-color: $background !default

### ISSUE THREAD

**Issue by bifunctor** [jgthms/bulma#1914]
Hi all 

I had try to override `navbar-height` variable as following:

```
@import "~bulma/sass/utilities/initial-variables.sass";
@import "~bulma/sass/components/navbar.sass";

@media only screen and (min-width: $desktop) {
  $navbar-height: 5.0em;
}

```
and the sass compiler complains:  

```
RROR in ./src/index.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--6-2!./src/index.scss)
    Module build failed:
    $navbar-box-shadow-color: $background !default
                             ^
          Undefined variable: "$background".
          in /home/developer/Desktop/reason-react/cockpit/node_modules/bulma/sass/components/navbar.sass (line 3, column 27)

```  
At the end of the file, I did import 

`@import "~bulma/bulma.sass";
`
I am using version `0.7.1`.  
Thanks

**Comment by jgthms** [comment]
Try importing the derived variables too.

**Comment by bifunctor** [comment]
What are the derived variables?   
How can I set, that the navbar on the `>= desktop` should be bigger than `<= desktop`.  

Thanks

**Comment by jgthms** [comment]
You can’t set a new value for Sass variable only for desktop. You have to write the CSS yourself.

**Comment by raniesantos** [comment]
I'm going to jump on this issue because my problem is related to this variable.

In the past versions, the box-shadow used `hsla` in its value.

Now it uses a solid color.

This is bad because the shadow now appears as an ugly solid line below the navbar. This isn't always immediately obvious depending on the layout, but here are screenshots.

![633ef21a-3e40-41af-8ce9-7f9b65019b58](https://user-images.githubusercontent.com/8528269/44798364-d38d9f80-abe3-11e8-8fe1-66dad01015a2.png)

![screenshot from 2018-08-31 16-55-16](https://user-images.githubusercontent.com/8528269/44903296-bfaa8080-ad3e-11e8-9c68-e981f97cd51a.png)
