### ISSUE TITLE
[Enhancement] input[type="radio"].button

### ISSUE THREAD

**Issue by Gaelan** [jgthms/bulma#193]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I am sure this issue is **not a duplicate**?

### Description

It would be really nice to be able to style radio buttons as "real" buttons. These would usually be add-on style (in fact, the existing example for add-on style buttons, a word processor control, could be implemented as a radio button under the hood), but they don't necessarily have to be.

**Comment by jgthms** [comment]
Do you have a screenshot or an example?

**Comment by Gaelan** [comment]
Something along these lines: (this is an example from a native OS X app, but it's the same concept)
![](https://thumbs.gfycat.com/AnimatedGranularKestrel-size_restricted.gif)
It looks like a set of segmented buttons, but behaves like a set of radio buttons (having one selection, deselecting others when clicked).

**Comment by tquetano-r7** [comment]
So I was playing around with this idea, because the way to do it in CSS would require a little extra markup, and before submitting a PR I wanted to make sure it gave @Gaelan what he was looking for.

The HTML:

```
<div class="control has-addons">
	<div class="input-button-group is-success">				
		<input name="test" type="radio" value="1" />
		
		<label class="button">
			Success
		</label>
	</div>
	
	<div class="input-button-group is-info">
		<input name="test" type="radio" value="2" />
		
		<label class="button">
			Info
		</label>
	</div>
	
	<div class="input-button-group is-danger">
		<input name="test" type="radio" value="3" />
		
		<label class="button">
			Danger
		</label>
	</div>
</div>
```

Far as the naming conventions go, the `input-button-group` was just me spitballing. The main point is that you need a container for both input and label.

The CSS:

```
.input-button-group {
	position: relative;
}

.input-button-group > label {
	z-index: 0;
}

.input-button-group > input[type=radio],
.input-button-group > input[type=checkbox] {
	cursor: pointer;
	left: 0;
	height: 100%;
	opacity: 0;
	position: absolute;
	top: 0;
	width: 100%;
	z-index: 1;
}

.input-button-group.is-info > input[type=radio]:checked + label,
.input-button-group.is-info > input[type=checkbox]:checked + label {
	background-color: #42afe3;
	color: #fff;
}
```

The `is-info` thing is just an example of how the different color mechanisms could be applied. The key here is:
* input before label in `input-button-group`
* container has `position: relative`, with input being `position: absolute`, filling the space of the container
* `z-index` is applied to both `input` and `label` to ensure that the `input` is clickable
* Identification of what button is selected is through pseudo-selector `:checked`, combined with the `+` operator to select next sibling

Did a quick jsfiddle for it => https://jsfiddle.net/exxpqkng/

If the extra markup is something that is acceptable, I can submit a formal PR for this. Let me know thoughts.

**Comment by jgthms** [comment]
@Gaelan Can't you use the `.tabs.is-toggle` from http://bulma.io/documentation/components/tabs/ ?

![screen shot 2016-05-08 at 3 10 07 pm](https://cloud.githubusercontent.com/assets/1254808/15098216/090a837e-152f-11e6-9151-f0d8a1632e9e.png)

**Comment by Gaelan** [comment]
Perfect! The extra markup is definitely acceptable.

**Comment by tquetano-r7** [comment]
Seems that @jgthms had an alternative idea ... rather than submit a PR that could duplicate functionality, see if the `.tabs.is-toggle` could work for you.

**Comment by jgthms** [comment]
@Gaelan Btw, there's the button addons as well: http://bulma.io/documentation/elements/button/

![screen shot 2016-05-08 at 8 46 20 pm](https://cloud.githubusercontent.com/assets/1254808/15099998/f9baead8-155d-11e6-8b5d-f5e48c3a372a.png)

**Comment by mokhosh** [comment]
I think the whole point of enhancing radio buttons is that we don't need to use Javascript to change classes.

**Comment by jipiboily** [comment]
If anyone need this, I did something that's not elegant but works in a few minutes. Here it is: https://gist.github.com/jipiboily/cfd8494fe174eb2a7f6202220196492a

![](https://dl.dropboxusercontent.com/content_link/dpkU9ad3kdO3wPYoHY2qnZ2hD3Ta2NnTUsMeUYDJ6SXsACAtpjDC5brHkWP8fou0/file?dl=0&duc_id=JQXpRXYg6hMaKgzF3geRZkonKpkzAbtKTweWcAkZFL9wjpmAIfjJy0dbBhHDCNz7&raw=1&size=2048x1536&size_mode=3)
