### ISSUE TITLE
Narrow Columns Documentation Incorrect

### ISSUE THREAD

**Issue by brandonaaskov** [jgthms/bulma#1990]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.7.1]
My **browser** is: Chrome 67.0.3396.99

### Description
In the section on using `is-narrow`, in the example on the page the flex column _doesn't_ fill up the remaining space as needed. It looks like the `is-narrow` column is still taking up the full width:

![image](https://user-images.githubusercontent.com/445778/42697249-954cdea0-8688-11e8-9764-abff2d415161.png)

### Steps to Reproduce

1. Go to [the Bulma docs on Narrow columns](https://bulma.io/documentation/columns/sizes/#narrow-column)
2. Resize your browser: at 768px the columns stack

### Expected behavior
The `is-narrow` column would stay at its fixed 200px width, and the flex column would resize to fit alongside it.

### Actual behavior
The columns stack into a vertical column instead of staying in the single row. This might be expected behavior, but the docs make it seem like it should not be doing that since it says "This column will take up the remaining space available."

**Comment by VizuaaLOG** [comment]
This is the expected behaviour. On mobile, all columns stack no matter what sizes they have. To keep the same behaviour that exists on desktop you just need to add `is-mobile` to the `.columns` element, this will respect size modifiers such as `.is-narrow`, `.is-expanded`, `.is-4` etc.

The screenshot below is the same part of the docs after adding `is-mobile`.

<img width="688" alt="screen shot 2018-07-25 at 23 53 53" src="https://user-images.githubusercontent.com/4404472/43231909-49658194-9066-11e8-99ab-67ff318fd113.png">

**Comment by jgthms** [comment]
Indeed. The columns are stacked on mobile unless the `is-mobile` modifier is used.

**Comment by brandonaaskov** [comment]
Ah, we had the `is-mobile` modifier on the wrong element then. Thank you for clarifying!
