### ISSUE TITLE
Dependency is not compatible with node 10

### ISSUE THREAD

**Issue by erfanio** [jgthms/bulma#2002]
This is about **Bulma**.

### Overview of the problem
One of the dependencies is not compatible with node 10

### Description
`yarn install` on master will result in the following

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". 
```

npm doesn't respect engine requirements for some reason.  
Lastest `upath` has fixed this problem, so a simple updating dependencies will fix it.

**Comment by VizuaaLOG** [comment]
`upath` isn't actually being directly used by Bulma. Unfortunately, I think you'll need to wait for the direct dependencies to update their version requirements which Bulma will most likely automatically pick up due to versions using `^`. A workaround would be to downgrade to node 9, although this may not be possible depending on your requirements.

**Comment by fibo** [comment]
Does it work (I mean everything works) using npm instead of yarn?

Consider that is unlikely that a module working with node v9 will not work with node v10.
