### ISSUE TITLE
add class "is-secondary"

### ISSUE THREAD

**Issue by paolobattistella** [jgthms/bulma#2183]
It is a feature request about Bulma  **CSS framework**.

Could you evaluate to add the class "is-secondary"?
It should be helpful in this case:
```
<form>
[...]
<div class="field is-grouped">
  <div class="control">
    <button class="button is-primary">Submit</button>
  </div>
  <div class="control">
    <button class="button is-secondary">Cancel</button>
  </div>
</div>
</form>
```

Best regards,
Paolo

**Comment by jgthms** [comment]
What color would that be?

**Comment by paolobattistella** [comment]
> What color would that be?

the default color could be $grey-lighter

**Comment by weyert** [comment]
You can already easily add this secondary colour by customising the colours. In my charity project I am using the following:

```
$secondary: #8BC91D;
$secondary-invert: findColorInvert($secondary) !default;

$custom-colors: (
    "secondary":($secondary, $secondary-invert),
);
```

**Comment by Dinuz** [comment]
If you also want to use classes like "is-secondary" or "has-text-secondary" you should follow what @weyert said, but with a small update at the end, you need to add $colors: map-merge($colors, $custom-colors);

`
$secondary: #8BC91D;
$secondary-invert: findColorInvert($secondary) !default;

$custom-colors: (
    "secondary":($secondary, $secondary-invert),
);
$colors: map-merge($colors, $custom-colors);
`
Otherwise it will not allow you.

**Comment by laurensV** [comment]
The `$custom-colors` is really helpful 👍  Should be included in the documentation!
