### ISSUE TITLE
Different column sizes in different breakpoints 

### ISSUE THREAD

**Issue by cihanzengin** [jgthms/bulma#2287]
Hello i want to do 

```
<div class="columns">
      <div class="column is-8-desktop is-mobile-6"></div>
      <div class="column is-4-desktop is-mobile-6"></div>
</div>
```

but it's not working so on mobile next column going to next row. why?

**Comment by jdriviere** [comment]
@cihanzengin Hello. I noticed that you did this:

```html
<div class="columns">
      <div class="column is-8-desktop is-mobile-6"></div>
      <div class="column is-4-desktop is-mobile-6"></div>
</div>
```

I think the problem is your __is-mobile-6__. I think it should be __is-6-mobile__. But that would only make the columns' length spread 50% of the container, but stacked up instead of being on one row. If you're wondering why the columns stack up instead of staying on one row (when in mobile breakpoint), it may be how the grid is set up.

**Comment by cihanzengin** [comment]
> @cihanzengin Hello. I noticed that you did this:
> 
> ```
> <div class="columns">
>       <div class="column is-8-desktop is-mobile-6"></div>
>       <div class="column is-4-desktop is-mobile-6"></div>
> </div>
> ```
> 
> I think the problem is your **is-mobile-6**. I think it should be **is-6-mobile**. But that would only make the columns' length spread 50% of the container, but stacked up instead of being on one row. If you're wondering why the columns stack up instead of staying on one row (when in mobile breakpoint), it may be how the grid is set up.

Hello, sorry my mistake :) , yes i fix it but again not worked. 

but..  when add yo **columns** class **is-mobile** class everything worked well. 

```
<div class="columns is-mobile">
      <div class="column is-8-desktop is-mobile-6"></div>
      <div class="column is-4-desktop is-mobile-6"></div>
</div>
```

**Comment by jdriviere** [comment]
Glad it was solved. :smile:
