### ISSUE TITLE
Bulma CSS button always next to various inputs or selects

### ISSUE THREAD

**Issue by MontoyaAndres** [jgthms/bulma#2312]
This is about the Bulma **question**
I'm using Bulma **0.7.2**
My **browser** is: Chome and Firefox

I want to have the delete button next to 2 select or inputs using the columns properties, but I have this

![screenshot from 2019-01-10 22-29-37](https://user-images.githubusercontent.com/15065852/51058909-583bf180-15b8-11e9-8085-aca4e4b2dee8.png)

I want to have that delete button next to those elements, in the middle, like this:

![screenshot from 2019-01-10 22-36-36](https://user-images.githubusercontent.com/15065852/51058925-668a0d80-15b8-11e9-8647-13ba2275340b.png)

And if the screen is small, that button always maintain there...

[Here](https://codepen.io/montoyaandres/pen/zymdVx) a little example.

Someone know how can do it? Thanks :D

**Comment by diomed** [comment]
hey, Andres

this code isn't what you're looking for, but I think it's even better,
because it puts x icon inside of input.

```
      <div class=" control has-icons-right">
        <input class="input is-hovered" placeholder="Social network link" required />
        <span class="icon is-medium is-right">
                    <i class="delete is-medium"></i>
</span>
      </div>
```

That way it doesn't stick out.

You can see it in use here: https://dansup.github.io/bulma-templates/templates/kanban[search].html
tho this was made in vue, and you're using react, so you'll have to change this and that, I guess, but 
all in all, design wise, it should be helpful.

**Comment by MontoyaAndres** [comment]
Thanks! But... How did you know I'm using react 😐?

**Comment by diomed** [comment]
just by hovering over your avatar. 😸
