### ISSUE TITLE
Conflict between dropdowns

### ISSUE THREAD

**Issue by gio00** [jgthms/bulma#2359]
### Overview of the problem

This is about the Bulma **CSS framework**. I think it's a bug. 

### Description

The problem happen with multiple dropdown. Let's say someone want two different navbar, both of them with some dropdowns. With this scenario a conflict happen between the dropdowns.

### Steps to Reproduce

I have copied two navbars from the docs and used version 0.7.4 of Bulma. Here's a code pen: https://codepen.io/anon/pen/rPvxvq

### Expected behavior

I think the upper dropdown should be usable too.

### Actual behavior

The upper dropdown has some of the available options hidden behind something. The second dropdown works fine.

**Comment by VizuaaLOG** [comment]
I don't believe this is a bug but just a side effect of CSS. The navbar has a higher z-index than the dropdown, causing the second navbar to appear in front of the dropdown from the first navbar.

Because websites/webapps come in a wide range of shapes and sizes, this would be simply dependent on the use case. So in this example, adding some custom CSS to the first dropdown increasing it's z-index to be higher than the navbar will allow it to show over the top.

From what I see this isn't something that's 'fixable' within Bulma, as it's very project dependent.

**Comment by gio00** [comment]
@VizuaaLOG Yes, you are right. The class `.navbar` has an explicit z-index so the dropdown is restricted under the navbar. Because the navbar is parent of the dropdown. 

Removing the explicit z-index (of 30) from the `.navbar` class fixes the problem. But I do not know the implication of this action framework wise.

Although, overriding the lower navbar with a lower z-index also fixes the problem.

**Comment by abnersajr** [comment]
Probably you are facing the same issue previously discussed here in the #2294 issue.
If really is the same issue, could we close this issue?
