### ISSUE TITLE
Typography Responsive sizes documentation wrong

### ISSUE THREAD

**Issue by erinsiren** [jgthms/bulma#2442]
This is about **Bulma | the Docs**.

### Overview of the problem

 This is about the Bulma **Docs** 

### Description

In the Documentation for typography helpers, using "is-size-1-tablet" should correlate to media query Between 769px and 1023px only. However, it is correlating to media query min-width: 769px and is therefore effecting everything larger than 769px which contradicts the documentation table.

### Expected behavior
is-size-1-tablet should only effect width that is between 769 and 1023px.

### Actual behavior
is-size-1-tablet is effecting everything above 769px width.

**Comment by nandaleite** [comment]
Hi @erinsiren. The actual behavior of ``is-size-1-tablet`` is correct and it should affect all screens above 769px. But you observed right, the table shows as if it is restricted to tablets only. I sent a pull request to fix the documentation page. 
The expected behavior you mentioned should be achieved by a supposed ``is-size-1-tablet-only``.
I would suggest to open a new issue requesting to include this responsive size for tablet-only.
