### ISSUE TITLE
Rename breakpoints to make sense with custom values

### ISSUE THREAD

**Issue by jdjoshuadavison** [jgthms/bulma#2485]
This is about **Bulma**.

It is a feature/question.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.5

### Description

Would you be willing to change the breakpoint names? They currently only make sense if you use the default values. If someone was to change these default values, as I intend to, the names will no longer make sense. A more generic/less specific naming convention would allow people to redefine the breakpoints as they wish and it will still make sense.

A suggestion could be: `smallest`, `smaller`, `medium`, `larger`, `largest`
or the bootstrap way: `extra small (xs)`, `small (sm)`, `medium (md)`, `large (lg)`, `extra large (xl)`
or even just sequential: `breakpoint 1 (bp1)`, `breakpoint 2 (bp2)`, `breakpoint 3 (bp3)`, `breakpoint 4 (bp4)`, `breakpoint 5 (bp5)`

**Comment by jgthms** [comment]
I'd argue that this would make the breakpoint names _less_ semantic. What does `medium` mean? Is it for a tablet? Or desktop? I find using `smaller` or `larger` quite obscure actually. They don't really mean anything to me, unless I've defined them myself.

An option would be to make these names customizable. But each of these breakpoint is available as a mixin as well, like `+tablet` or `@include tablet`. AFAIK you can't have variable names for mixins.

**Comment by jdjoshuadavison** [comment]
I'd agree that, if you use the default values, the names `mobile` and `tablet` are more semantic, _but_ they become _incorrect_ if you customise the values, which seems like a bigger problem. So I guess I'm not discussing semantics, rather, flexibility. (I may edit original post to reflect this).

I had also thought of making the names customisable, but also wasn't sure about the possibility of using variables as names for mixins, as well as concerned about added complexity.

**Comment by jgthms** [comment]
Yeah, dynamic mixin names are still not available: https://github.com/sass/sass/issues/626

You can however create your own breakpoints like `$small: 600px` and invoke it with Bulma's `+from` and `+until` mixins:

```sass
.component
  color: red

+until($small)
  .component
    display: none

+from($small)
  .component
    color: blue
```

**Comment by emkajeej** [comment]
I'd argue against @jgthms's point in this regard. `mobile`, `tablet` is too descriptive and also not very flexible. There are mobile devices that have a higher resolution than certain tablets. To target those I would have to go against the current naming convention. How about desktop browsers with smaller windows (not screens)? Not everybody browses in fullscreen.
Secondly responsive design should be based on screensize rather than device type. So even though `small` doesn't make sense to an end-user, it's only the developer, ie the person(s) working on the project, who will be using these terms which would be defined in earlier development stages.
To me it's the reason we're using `is-primary` over `is-turquoise`.

**Comment by jdjoshuadavison** [comment]
I can see both sides of the argument. On the one hand, as @emkajeej says, it shouldn’t be about device but about size. On the other hand `extra small`, `small`, `large` and `extra large` don’t tell you anything about their actual size either. I guess the ideal solution would be if the breakpoints contained their widths in their name, e.g. `bp768` for max width 768px and `bp960` for max-width 960px etc...

**Comment by jdjoshuadavison** [comment]
This does bring me on to another point which is the `touch` mixin. Touch is defined as "until 1023px". This is an equally bad (if not worse) assumption. We already have the Surface Pro's which are fully touch capable and run at a viewport width of 1368px. We also have plenty of people who don't use their browsers at maximum window size, easily falling below the 1024px breakpoint and definitely not touch capable. 

What is also confusing me is that for the following "until" mixins, you've just called them, `until-widescreen` and `until-fullhd`. Putting aside the argument of whether you should be using device-based names for your breakpoints at all, why not be consistent and call it `until-desktop` instead of `touch`?

**Comment by KayakinKoder** [comment]
As a longtime bootstrap user thinking about using bulma for our next ui update, I definitely agree that generic small/medium/large naming conventions would be preferable. One of the very few "negative" thoughts I've had about bulma while scanning the docs is "hrm, after I change the breakpoints to where we want them the naming conventions won't be relevant anymore, which is going to be confusing for new devs our devs who just pop in to the frontend css from time to time"

**Comment by hanscees** [comment]
Hi, I'm header of IT in some organization. We just rolled out 350 touch-enabled windows HP 13"  laptops. Your touch semantics is a bit outdated since these devices are becoming the norm fast in this world. They are all both widescreen and touch.

As I noted in some bulma github issues, the is-hover is broken if you use a wide touch-device and click on drop-down navbar items as you do when you touch a touch-device with your finger instead of use a mousepointer that can hover . So your own assumptions that small devices are touch is biting bulma actively now so it seems to me.

Another problem I have with the current definitions for instance is with the gap between mobile and tablet brakepoints. The navbar uses mobile as a breakpoint, but I want the hamburger menu at 768. This results in a hamburger menu that does not work between breakpoint mobile and tablet.

How to resolve this?  I have not yet studied how you can alter variables in the bulma way of thinking (with sass) but a suggestion could be:

Sematics
let tablet standard be 1024, let mobile standard be 768 and so on
Allow overrides: so if I want the tablet brakepoint to be 860 on some device:
 first define hc-tablet = 860 (or any other name like big-tables, or tablet-2025)
 then tell bulma to use this definition as its " tablet brakepoint". 

so something like: hc-tablet=860; tablet-brpt=hc-tablet, or is-hc-tablet {tablet = 860}

Why not just tablet=860? Thats less flexible. 

Implementation
I would like such overrides to be usable without installing and re-making some sass thing and creating another version of the css version. I would favor a simple addition via css like
is-hc-tablet {tablet = 860}

Just my two cents.

**Comment by hanscees** [comment]
Have been thinking some more. 

Why not generate several bulma.css files with different brakepoints? 

bulma-mobile.css (brakepoint at 768 in stead of 1024)
