### ISSUE TITLE
Horizontal form fields not the same width inside modal

### ISSUE THREAD

**Issue by claide** [jgthms/bulma#2551]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework** 

### Description

I added a horizontal form inside a modal with a specific column size. Starting in 769px screen width, the form fields specifically with a short label the input element spans the available space.
Now, when I add other fields with a longer label, they get different input width sizes.

### Steps to Reproduce
[this is the working demo](https://jsfiddle.net/bawvs8kx/)

### Expected behavior

What I would like to achieve is for the fields to have the same input widths regardless of the label length.

### Actual behavior

Please see the working demo above. As what you can see, the E-mail label is short and its input spans the whole available space and produces not uniform form fields inside the modal.

**Comment by james-wasson** [comment]
This is actually an issue with you wrapping the `.field` in the `.columns`. If you remove the `.columns` this issue goes away. If we take a little closer look we can see the issue belongs in the style `flex: none;` if we disable this the form is displayed somewhat how it is supposed to be.

The real issue is with how you are centering and limiting your form to be a certain size. I don't think Bulma comes shipped with a way to limit the size of a form and center it. In this case I would recommend some custom CSS to accomplish this trick.

Let me know if this makes sense to you.

**Comment by james-wasson** [comment]
After removing the `.columns` and `.column` `<div>` tags try the following CSS:
```CSS
.form-horizontal {
  width: 80%;
  min-width: 350px;
  margin: 0 auto;
}
```

**Comment by claide** [comment]
@james-wasson yes working great. I made it working using nested column but, your suggestion is very clean! Thanks again
