### ISSUE TITLE
Could you please add more form components into bulma?

### ISSUE THREAD

**Issue by dayAndnight2018** [jgthms/bulma#2556]
This is about Bulma.

I suggest that bulma should add more flexible components such as datepicker, timepicker, timerline and so on.

Are they in your schedule?

**Comment by jgthms** [comment]
They’re not planned because they would require Javascript and they’re too specific for a general use case. I don’t want to bloat the framework with components that are only used by a few users. 

However, that’s the reason behind Bulma extensions: https://bulma.io/extensions/
This allows developers to add functionalities to Bulma without having to add them to the core framework.
