### ISSUE TITLE
How to animate modal show / hide ?

### ISSUE THREAD

**Issue by gbourgneuf** [jgthms/bulma#257]
Hi,

is there a way to animate the modal show and hide ? 
I tried using transform css rules without success. I also tried using flex-grow.

For example: how can I animate my modal by fading and scaling up when activating it ?

Regards

**Comment by jens1o** [comment]
>  how can I animate my modal by fading and scaling up when activating it ?

Using https://daneden.github.io/animate.css/ `animate.css`:

import `animate.css`, then just add the classes `animated fadeIn` to your modal like so:
`<div id="yourmodalidhere" class="modal animated fadeIn">`

Don't use transitions, because they are also active if it is hidden. Keyframes only will be executed if the element is not hidden.

>  scaling up

? Do you mean the Zoom-IN animation of animate.css?

**Comment by gbourgneuf** [comment]
Perfect :-)

Yes I meant Zoom-In animation when saying "scaling-up".

Thank you.
