### ISSUE TITLE
[REQUEST] Making Bulma even cleaner and more structural

### ISSUE THREAD

**Issue by veryverygoodgood** [jgthms/bulma#2719]
Bulma is supposed to be a cleaner, simpler alternative to Bootstrap. While that's certainly true, it still has some way to go.

https://en.wikipedia.org/wiki/Semantic_HTML.

@jgthms argues that semantic HTML does not apply to class names. That is simply not the case, as Bulma's classes need to be inside the HTML. 

Good semantic HTML means it should have tags and classes that reflect the structure or meaning of its content, and not its looks. Although the nature of CSS frameworks require us to use classes that represents looks, it doesn't mean we can't use meaningful names or have clean structures.

In the the far future, however, we might see CSS frameworks where classes being assigned to perfectly semantic HTML through some middle layer. But for now, let's clean up Bulma.

- Bulma general requirement of tag inside tag inside tag is one example of it polluting the structure and meaning of the HTML.

- Class names with unclear meaning such as `is-1`, `is-2` etc. These might need to work in tandem with other classes that provide more meaning, but alone they don't make any sense. Also, we should avoid using numbers where possible and use `small`, `medium`, `big` etc.

- Another is the use of 90s style tags such as `<strong>`, `<small>`, `<hr>` etc. when these could be classes such as `has-strong-text`, `has-small-text`, `has-horizontal-ruler` etc.

- Sometimes unclear where classes should be assigned. Directly on the element or through one of its parents? Depending on the situation, sometimes the former works and sometimes the latter. It should work on both.

- There should be no need for unnecessary repetition of classes such as `navbar-item` when it should be obvious that items within the navbar are just that - items. In addition, in semantic HTML `<ul>` and `<li>` would be the more proper.

Ie. why can't this:

```
<section class="hero is-white">
  <div class="hero-head">
    <nav class="navbar is-transparent">
      <div class="container">
        <div class="navbar-brand">
          <a href="#" class="title navbar-item">MyLogo</a> <-- Bulma should know this is the logo since its parent's name is "navbar-brand"
        </div>
        <div class="navbar-menu">
          <div class="navbar-end">
            <a href="#" class="navbar-item">Link 1</a> <-- Same here, Bulma should know this is a navbar item
            <a href="#" class="navbar-item">Link 2</a>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>
```

Be more like this:
```
<section>
  <div class="container hero is-white is-transparent">
    <nav>
      <div class="brand is-left">
        <a href="#" class="title">MyLogo</a> 
      </div>
      <ul class="menu is-right">
        <li><a href="#">Link 1</a></li>
        <li><a href="#">Link 2</a></li>
      </ul>
    </nav>
  </div>
</section>
```

Hopefully Bulma, with all its funding and public backing, can make something like this happen in the near future.

Thanks!

--VVGG

P.S. Someone please make a subreddit or something so we can discuss cases like these without having our issues closed and therefore hidden from public view.

**Comment by jgthms** [comment]
> @jgthms argues that semantic HTML does not apply to class names. That is simply not the case, as Bulma's classes need to be inside the HTML.

Having descriptive CSS class names is useful, and Bulma has them: `tabs` `breadcrumb` `navbar` `pagination`… These names describe the content, not necessarily how the component looks. But you'd be mistaken to think these class names were parsed by crawlers to apply meaning to a webpage. It's the use of semantic HTML elements that's crucial, not the CSS class names.

> * Bulma general requirement of tag inside tag inside tag is one example of it polluting the structure and meaning of the HTML.

When it's possible, Bulma will use a semantic structure. For example:

* https://bulma.io/documentation/components/tabs/ use an unordered list `<ul>`
* https://bulma.io/documentation/elements/table/ uses `<table>`
* https://bulma.io/documentation/elements/title/ uses `<h1>` `<h2>`…

> * Class names with unclear meaning such as `is-1`, `is-2` etc. These might need to work in tandem with other classes that provide more meaning, but alone they don't make any sense. Also, we should avoid using numbers where possible and use `small`, `medium`, `big` etc.

If we use `small`, `medium`, `big`, you're describing how the component looks, not what it means. So I'm not sure how it applies to your idea of "semantic HTML"?

> * Another is the use of 90s style tags such as `<strong>`, `<small>`, `<hr>` etc. when these could be classes such as `has-strong-text`, `has-small-text`, `has-horizontal-ruler` etc.

`<strong>`, `<small>`, `<hr>` are perfectly fine semantic elements. For example, the `<strong>` element represents text of certain _importance_.

I think you're confusing them with `<b>` and `<i>`, which _are_ from the 90's. You should read about `<b>` for example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b

And if you use `has-strong-text`, `has-small-text`, `has-horizontal-ruler`, you're going _against_ semantic HTML actually… Because you're removing the meaning of an HTML element, and only care about how it looks?

> * Sometimes unclear where classes should be assigned. Directly on the element or through one of its parents? Depending on the situation, sometimes the former works and sometimes the latter. It should work on both.

It can't work on both. That's not how CSS works. The selectors depend on the HTML hierarchy. See https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator for example

Bulma provides HTML examples to explain on which element the classes should be applied, and what HTML structure should be expected.

In general, Bulma wants to separate the meaning (through HTML) and the looks (through CSS). Users are free to use the semantics they need in HTML without having to worry about the styling. That way, they can use `<a class="button">Anchor</a>` or `<button class="button">Button</button>` depending on the element they need, while still having the same style applied in both cases.

Hope this helps.

**Comment by veryverygoodgood** [comment]
@jgthms could you please stop closing these issues before I even get a chance to reply?

I have a lot of things I wish to clear up with regards to your reply. And this is not criticism, but rather constructive criticism. Because like everyone else here I'm also in love with Bulma. So please don't get the wrong idea thinking I'm out to make Bulma look bad.

Could you please re-open this issue so we can finish this discussion before you close it again?

Thanks, and have a good one!
