### ISSUE TITLE
Remove .DS_Store artifacts from library uploaded to unpkg

### ISSUE THREAD

**Issue by covamalia** [jgthms/bulma#2770]
Using Libman to handle Client-Side Libraries in Visual Studio 2019 for Windows (have tried in both 16.5.0 Preview 1 and 16.4.0 both with same error), you get an error when downloading these from unpkg, as Libman cannot download the `.DS_Store` files for the library.

These files are located in:

`/sass/.DS_Store`

`/sass/utilities/.DS_Store`

With these included in the release, you have to manually specify which sass files to download, which means more maintenance should more features be added using additional sass files.

As these are not relevant to the functionality of Bulma, I would suggest excluding these from the deployment process.

**Comment by covamalia** [comment]
And a couple of screenshots of this:

![1](https://user-images.githubusercontent.com/9821870/72456479-a6339880-37bc-11ea-9436-b81882f30a32.png)
![2](https://user-images.githubusercontent.com/9821870/72456491-aaf84c80-37bc-11ea-9464-99f1d285a019.png)

**Comment by covamalia** [comment]
Just done some more investigating and this isn't an issue when getting the same files with jsdelivr in Libman, which does download all files (including `.DS_Store` ones), so there is a workaround.

Would still be good to remove the files from releases though. Not sure why they would be in there as I checked the .gitignore and the filetype is contained in there.

**Comment by portalhoy** [comment]
These files are created by Finder and even deleting them reappear. But well, if we move on Mac OS X there are no problems because they always appear hidden. The problem arises when we do it on network drives that we have shared with Windows systems that will show them. But via terminal is something we can solve. To do this we will open our terminal and type:
`defaults write com.apple.desktopservices DSDontWriteNetworkStores true`

Vía: https://www.applesfera.com/os-x/evita-la-creacion-de-ficheros-ds_store-en-unidades-de-red
