### ISSUE TITLE
NavBurger disappears with Night Mode on Samsung Internet Browser

### ISSUE THREAD

**Issue by awhitford** [jgthms/bulma#2807]
### Overview of the problem

I have a basic web site that uses the traditional [navbar-burger](https://bulma.io/documentation/components/navbar/#navbar-burger) with JavaScript toggle.

When using *Samsung Internet Browser* with *Night Mode* enabled (aka *Dark Mode*), the burger is practically hidden -- it is basically black on black, so the button works if you know it is there, but it isn't obvious that it is there.

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.8.0
My **browser** is: *Samsung Internet Browser* 
I am sure this issue is **not a duplicate**

### Steps to Reproduce

If you have a Samsung phone, just activate Night mode and then pull up bulma.io using _Samsung Internet Browser_ (not Chrome).

Alternatively, you can run a Samsung Simulator for free here:  https://developer.samsung.com/remote-test-lab

### Expected behavior

The text gets reversed in Night Mode, so that displays fine.  However, the burger spans aren't changing color, so they are black on black.

I need the burger to be visible in Night Mode AND Light Mode.

**Comment by da2x** [comment]
This is difficult to fix because its the browser that is broken. It does [strange things with colors in night mode](https://www.ctrl.blog/entry/samsung-internet-night-mode.html) and ruins contrasts. You can’t even detect night mode, it doesn’t support  `prefer-color-scheme` media queries, and it doesn’t update the colors it uses in the `window.getComputedStyle`API.
