### ISSUE TITLE
Screen size dependent spacing helpers

### ISSUE THREAD

**Issue by ambrt** [jgthms/bulma#3016]
Is it a bug/feature/question or do you need help? **Feature**

All helpers from https://bulma.io/documentation/helpers/spacing-helpers/ like `pb-1` could have their counterparts of `is-mobile` like `pb-1-mobile` - so padding would be added only on mobile screen size.

**Comment by nedjo** [comment]
Breakpoint support didn't make it into the commits in #451 where spacing support was added; see https://github.com/jgthms/bulma/commit/a2a9564ca9efb643cb3992a83f9df802159449c4#diff-638e23261295b3336ed9b3561484828d. From @jgthms in [that issue](https://github.com/jgthms/bulma/issues/451#issuecomment-612836802):

> I'm not sure how to handle responsiveness, in order to have mobile/tablet/desktop/widescreen/fullhd version of each spacing helper. If following the above approach, you would have `m-0-mobile` and `m-2-tablet` that could be combined

**Comment by guillaumeprevost** [comment]
Bumping this feature request :)
 
Just a thought, another possibility could be to have a way to declare that a given spacing should be "responsive/fluid" so that when hitting a breakpoint it becomes smaller or larger automatically by a given percentage.
For example if my spacing "3" is 32px (so mt-3 is a margin-top: 32px), I could set the class "mt-3-fluid" so that it is 32px on desktop, 32*80% on tablet, 32*60% on mobile). 
Not sure whether this is the Bulma way...
