### ISSUE TITLE
.columns exceeds width of the page in a .hero-foot and adds whitespace at bottom of page

### ISSUE THREAD

**Issue by callum-ez** [jgthms/bulma#3023]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.9.0
My **browser** is: Chrome 83 (MacOS)

### Description

Placing a .columns element (with two columns) inside a .hero-foot element will cause the .columns element's width to exceed that of the display, which in turn causes the rest of the page to "squash", particularly on smaller devices.

### Steps to Reproduce

I've made a JSFiddle here: https://jsfiddle.net/qe4rpksw/

Although it's perhaps easier to see the problem in a full page since JSFiddle seems to have the bottom of the page cropped off for some reason, in which case one can just copy over the HTML to a local document.

### Expected behavior

The .columns element should be the same width as the rest of the page, for example the .hero-foot. There should be no whitespace underneath the .hero-foot.

### Actual behavior

The .columns element is wider than the page (it appears to be always by 24px). This also causes display issues on mobile because when the page gets shrunk down to accommodate this larger-than-the-screen element it squashes the .hero-foot element. There's also some whitespace underneath the .hero-foot.

![Screenshot 2020-06-29 at 15 51 17](https://user-images.githubusercontent.com/52198062/86021477-05aafb00-ba21-11ea-80f5-7cb3d86a2b8b.png)

**Comment by jaloplo** [comment]
Hi @callum-ez,  
It seems to be a problem of the `.hero` class instead of `.columns` one. If you use some _development browser tool_ to check the size of each of these items you will see that the one that doesn't fit the whole width is the `.hero` one.

Let me share with you this _JSFiddle_ forked from the one you've shared that solves the problem of the background colors, [https://jsfiddle.net/okv1Lwf2/](https://jsfiddle.net/okv1Lwf2/). Check how the background color is set on the `.columns` element and not in the `.hero-foot` one.

Regards.
