### ISSUE TITLE
Hover on navbar is always triggered in small screen

### ISSUE THREAD

**Issue by ambrt** [jgthms/bulma#3032]
This is about **Bulma**.

Is it a **bug**

1.Go to https://bulma.io/documentation/components/navbar/
2. Minimize screen.
3. All dropdown examples are auto-expanded.

Also hoverable navbar item, inside of brand turns into visible link on navbar
(instead of being activated on click or hover)
Here's fiddle https://jsfiddle.net/zd4ms97L/1/
Not sure if its a bug or done on purpose.

**Comment by mmarti** [comment]
I just ran into this issue myself. I have a very simple navbar with a single dropdown with a few options.  It seems to be impossible to get the navbar to work normally on small screens.  I don't need the dropdown to be responsive, which seemed like nesting it inside the `.navbar-brand` class would do the trick, but it awkwardly makes all the children visible in the navbar instead of as a normal dropdown.
