### ISSUE TITLE
Bulma, step up your game

### ISSUE THREAD

**Issue by LoopsGod** [jgthms/bulma#3074]
This is about **Bulma**.

### Description
I am opening this issue to help on improving the Bulma CSS framework. We currently use Bulma in production, but we've had several issues which we ended up having to solve by going to great wavelengths, which could be just easily fixed by merging a Pull Request.

How is it that a lot of popular issues do not really get addressed despite being very popular & being open since early 2018-2019, but I'm seeing sponsoring options everywhere?

I'm not trying to bash on Bulma or anything, we use it in production, but we've had tremendous amount of work in customisation and basic things Bulma does not provide out of the box (which, in my opinion, it should). I've also seen plenty of issues (which were great ideas) being quickly disregarded by the author, instead of being properly addressed.

In my opinion, it seems as though more work is being put in the sponsoring/commercialising of Bulma (which is everywhere, for some reason) than there is in actually improving the framework by useful features and optimizations. Bootstrap (and Buefy), for example, rarely or never even ask for sponsoring of any kind of financial compensations.

I am not against sponsoring or helping out, but community help such as issues & recommendations like these are worth much more than a couple sponsors (in my opinion).

@jgthms If you need to make a revenue in order to sustain Bulma, I'd recommend creating/building themes, like Bootstrap does, https://themes.getbootstrap.com/ -- and selling them in order to also provide value to end-users who would like to financially contribute by getting a theme & saving time in the process.

Again, great work on Bulma, but I've seen a lot of nearly instant negativity on issues being opened that actually contain great feedback & solutions. I've seen plenty of people having to create custom CSS in Bulma issues because the issue got disregarded and was never even closed as well.

#### Search
- Issue #2936. 
- Issue #1325, contains tons of people complaining about no response to issues. 

#### Docs
Plenty of people complain about the documentation having too many clicks, difficult searching & just lacking behind in terms of other documentation sites / options (such as, Vue.js, Bootstrap, etc.). 

#### Search
- Issue #2936. 
- Issue #1325, contains tons of people complaining about no response to issues. 

PRs mentioning the docs: https://github.com/jgthms/bulma/pulls?q=is%3Aopen+is%3Apr+docs -- contain plenty of pull requests with documentation improvements, not being merged.

There's way too much pull requests opened, with no response and nothing. Issues & feedback requests as well.

### Disclaimer
I didn't have time to list everything here, but if you just look thoroughly through every issue & Pull Request in this repository, you can see a lot of issues being quickly disregarded + pull request criticism & after that; no response. 

Instead of focusing on sponsors @jgthms -- you can improve the community, which would eliminate the need for financial support? I'm not very understanding of the desperate need for sponsors, if this is a community based / open source project anyway. No harm to you, but Bulma is the most commercialised repository / open source project I've ever seen on GitHub, or anywhere for that matter. I'd suggest making money some other way, like I mentioned (using Themes).

### Proposed solutions
Try getting new people / managers on board, move to a 'bulmacss' GitHub Teams, invite people and get more people in the repository.

**Comment by jgthms** [comment]
Hi @LoopsGod and thanks for sharing your thoughts.

I understand your concerns. There is still new features being built. The last release had [margin and padding helpers](https://bulma.io/documentation/helpers/spacing-helpers/) which the community really wanted. It took a while because I wanted to get it right. There was also RTL support which wasn't easy to add because I don't personally use it.

For all these things, I need to move slowly to avoid breaking things, and do too many changes. The key point is that it's easy to add features, much harder to maintain them. And while creating a PR is straightforward, there is no responsibility to maintain; I'm the only one who has that, so I need to be careful.

In terms of sponsorship, it helps but it's not enough to be sustainable on its own. It does seem it's being done more often than anything else, but sponsors change every month (and sometimes every 2 weeks), so it needs to be updated regularly. It does however take much less time than coding, so the frequency isn't really reflective of the time spent.

I have actually had plans to do official premium thems. Like everything else with Bulma, I don't want to simply get it done, but get it right. I wouldn't want to create half-baked that users wouldn't like, and that I wouldn't be proud of.

For that to work, I first need to finish adding CSS variables to Bulma. I've been working and thinking about it for the past year. There are different approaches to do it, some more straightforward than others. I could even add it tomorrow, but I need to think about maintainability and backward compatibility. I cannot ship a feature and remove it the next week. Here again, caution is key.

In any case, I'm still working on Bulma. Probably slower than what would be expected, but I think a lot of users do like the stability of the framework.

**Comment by abuassar** [comment]
@jgthms thanks for your wonderfull work, bulma is impressive.

And I'd like to personally thank you for adding RTL support, I'm an Arabic and RTL support is a must for me, even bootstrap doesn't have an official RTL support till now.

And about CSS variables I was just about to open an issue, asking for it, but knowing that it is already WIP is relieving, you may contact ionic-framework as they transitioned from scss (in v3) to css variables (in v4) and I used both and honestly css variables are far superior to scss variables!

**Comment by Tofandel** [comment]
Funny you should mention css variables...Yet you didn't even review #2981 ... Which "doesn't just get it done, but gets it right" as you said.

Anyways you've made it clear you don't want help from any maintainers so your comment just reinforces the fact that you need maintainers and not just sponsors

> For all these things, I need to move slowly to avoid breaking things, and do too many changes. The key point is that it's easy to add features, much harder to maintain them. And while creating a PR is straightforward, there is no responsibility to maintain; I'm the only one who has that, so I need to be careful.

Yet even RTL support was rushed and did break things see #2995 and it wasn't even done 100% properly

But trust me if you're not willing to just take 1hours to review a PR and approve or request changes and instead like to spend 20hours developing that feature yourself, this project will slip of your god ownership and a truly **open** source one will be created to address all the problems you haven't been willing to solve in the past 5 years when the community did at their cost and effort in usually a short amount of time.

You seem to think none of the PRs are perfect but yet you think all of your work is, disclaimer nothing is perfect so you should slightly step down on the perfectionism that hinders tremendously productivity

**Comment by rubjo** [comment]
Just wanted to chime in and say thanks to @jgthms for creating this excellent framework, and to support @connorshea in his plea for respect and as civil a tone as possible.

@Tofandel CSS variables support like implemented in your PR is something I've been waiting for in Bulma a while. It indeed seems like the project could benefit greatly from more maintainers – to an outsider, anyway. If you are able to pull it off like it sounds you might, I'm really eager to try out your fork.

**Comment by Tofandel** [comment]
There has finally been some movement in this project on the most pressing issues and I appreciate it @jgthms 

However my point regarding css variables and lack of maintainers still stand and I don't believe the general problem we are recurringly seeing will go away on it's own unless more maintainers are added and community feedback is taken into account.

On that note I started Bulba which is a fork of bulma trying to stay as compatible as possible so that it can almost be a drop in with the help of @LoopsGod (More maintainers are welcome as well), there is quite a lot of work to do before I can release it publicly with a new and improved documentation and theme builder

A few list of improvements planned or already implemented:

- [x] Sass linter to automatically lint all merged pull request, there is originally a guideline on bulma regarding code style but it never was enforced
- [x] SCSS mirror of the SASS code automatically deployed
- [x] Themeable support with CSS variables (my PR)
- [ ] RTL support using css variables and the dir attribute (so we don't have to include a separate stylesheet for ~40 lines of css)
- [ ] New breakpoint system using css variables as well (still in the brainstorm process)
- [ ] Vuepress documentation (yes with a search :eyes:)
- [ ] Theme builder on the documentation
- Theme sharing with votes on this same documentation

I already have plans with buefy to have it integrate Bulba

So I'd like to thank everyone for their mental support :muscle: and @jgthms for initially creating and maintaining this hugely amazing project :heart: which I'm now building upon

I'll keep you posted
