### ISSUE TITLE
Is it possible to change icon color with modifiers like "is-danger"

### ISSUE THREAD

**Issue by scottgrayson** [jgthms/bulma#310]
- [ ] This is about the Bulma **CSS framework**
- [ ] This is about the Bulma **Docs**
- [ ] I'm using Bulma **version** [0.1.2]
- [ ] My **browser** is: chrome
### Description

How can I change the color of the icons on the right side of this table?
http://bulma.io/documentation/elements/table/
<span> produces black
<a> produces primary
but modifier classes like "is-danger" don't have any effect
### Steps to Reproduce
1. http://bulma.io/documentation/elements/table/
2. open chrome dev tools
3. try to change icon color with modifier classes
### Expected behavior

changing colors with modifiers
### Actual behavior

modifier classes have no effect

**Comment by noomerzx** [comment]
If you looking to the raw bulma css file. You'll realise that they design some modifiers that work for some other class especially like .button.is-danger / .hero.is-danger. So .is-danger standalone is not working. The other modifier is work that way is "is-fullwidth"

I dont know it's bug or they design that way because it's has 2 modifier that can't use by standalone class.

**Comment by AlgusDark** [comment]
@jgthms I believe you can close this... with bulma you can use `has-text-danger` now is possible to do something like:
```
<span class="has-text-danger icon">
  <i class="fa fa-home"></i> // -> or if you want only the icon, you can use it here instead
</span>
```

**Comment by jgthms** [comment]
@AlgusDark Good shout.
