### ISSUE TITLE
Is Bulma ready for production or we have to wait for the v1 ?

### ISSUE THREAD

**Issue by zzseba78** [jgthms/bulma#312]
Is Bulma ready for production or we have to wait for the v1 to use it on a project ?

**Comment by jgthms** [comment]
Wait for v1! https://github.com/jgthms/bulma/projects/1

**Comment by uptownhr** [comment]
just trying to get a feel, estimated timetable available?

**Comment by jgthms** [comment]
My iMac died, so the development time is significantly slower for now. Waiting on the new MBPs...

**Comment by mesqueeb** [comment]
Waiting for v1 ♡

**Comment by eman1986** [comment]
is there an ETA on a v1 release? very interesting in using this for a new application I'm working on

**Comment by mfish0005** [comment]
@jgthms So it isn't stable enough to build a site with or are changes to the core functionality likely?

I ask because I plan on using it to build a portfolio site for my new employer.  Mainly for the grid system (and the tiles would be great for my sanity).  

Updating some things later wouldn't bother me that much...updating everything might though!

You do great work btw I actually like working with Bulma

**Comment by choonggg** [comment]
@jgthms it's a really good framework I'm happy to help get this to V1, is there an issue for tracking V1?

**Comment by jgthms** [comment]
Closing this one since Bulma is already used in production by many people. Best examples are here: http://bulma.io/expo/

**Comment by mesqueeb** [comment]
I hope just a little while longer until V1! ♡
Keep it up @jgthms 
V1 Will be a big marketing boost as well, as lot's of blogs would write about you!!!
