### ISSUE TITLE
[Feature Request] Add a search option on the main website

### ISSUE THREAD

**Issue by rajat2502** [jgthms/bulma#3144]
This is about **the Docs**.

It is a feature request.

### Overview of the problem
The documentation website should include a `search` option.

This is about the Bulma **Docs** 

### Description
The documentation website should include a `search` option so that anyone can easily search the `classes` they are looking for. Right now, one needs to go through the documentation to find the classes.

### Expected behavior
A search box on the top of the website/navbar.

**Comment by service-paradis** [comment]
There are already a lot of issues asking for this. The [main one from 2018](https://github.com/jgthms/bulma/issues/1325) is still opened. Someone even made a [PR](https://github.com/jgthms/bulma/pull/1622) to solve this a while ago. It is now outdated since there was no follow up on it.

And there is this list of duplicated issues:
- https://github.com/jgthms/bulma/issues/2970
- https://github.com/jgthms/bulma/issues/1784
- https://github.com/jgthms/bulma/issues/1765
- https://github.com/jgthms/bulma/issues/1595
- https://github.com/jgthms/bulma/issues/1403

Unfortunately, it looks like Bulma will never have a search functionnality.

**Comment by rajat2502** [comment]
> Unfortunately, it looks like Bulma will never have a search functionality.

Well, that's really sad to know. Not having a search option makes the development really slow!

**Comment by Lexpeee** [comment]
Commenting on this so that I could get notifications from this one. I'm also in need of a search bar.

**Comment by thomasedwards** [comment]
Meanwhile: [Tailwind UI implemented search](https://github.com/tailwindlabs/tailwindui-issues/issues/30) in 5 days

I’m moving my projects over to Tailwind one by one now. Also helps solving the accessability problems in #53

**Comment by Wisbell** [comment]
Is there any reason why it hasn't been implemented?

**Comment by thomasedwards** [comment]
@Wisbell not really no

You’re welcome to use the search that I built with a bit of help: https://bulmasearch.netlify.app

**Comment by SquidwardHill** [comment]
Commenting to bring attention to this as well. Unless I'm completely misremembering, Bulma previously had a search on their site...and somewhere in the redesign it was removed. This was an extremely helpful feature and would love to bring back!
