### ISSUE TITLE
Modal z-index is not working

### ISSUE THREAD

**Issue by ganga549** [jgthms/bulma#3156]
This is about **Bulma **.

### Overview of the problem
I am using Bulma Modal. The modal-content is not showing as the top; Instead I see it in the background. In my limited knowledge, the z-index is not working. Anybody else facing this issue? 

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.9.0]
My **browser** is: Chrome

**Comment by mijorus** [comment]
what do you mean with 'in the background'?

**Comment by VishwaJay** [comment]
I've actually had a similar issue, but it's beyond the scope of Bulma to fix (it's actually an issue within the browser).

The workaround I've found is to make sure the modal is AFTER all of the stuff you want behind it (nearest to the `</body>` tag). Then it will naturally pop up in front of everything, because of the way that all browsers render things.

Hope this helps!

**Comment by ganga549** [comment]
Thanks Vishwa.  Will try this out.
