### ISSUE TITLE
Where to ask questions?

### ISSUE THREAD

**Issue by guettli** [jgthms/bulma#3196]
This is about **the Docs**.

I have never used Bulma before.

I look at: https://bulma.io/

I would like to ask a question. But where? I could not find a link to a form, group or mailing list.

Please take this serious. New comers should have a place to ask questions.

**Comment by VishwaJay** [comment]
I thoroughly agree!

However, the problem with this idea is that places like StackExchange (and other places with so-called "experts") actively discourage newbies from asking questions that seem lame, newbish, or otherwise "low-quality" (a quality I find to be 100% subjective). So long as such a system actively prevents newbie questions, there won't be a good answer. And, I categorically refuse to participate in such sites so long as that remains the case (especially where multiple perspectives are actually beneficial).

However, I've been very, VERY pleased with the documentation in Bulma, and most of the additional questions I've had can be answered with some research into how CSS, SCSS, and SASS all work. 

Should there be a discussion where newbie questions are welcome, I'll happily join and help (not to mention, learning things myself). But overall, my online experience with this has been amazingly lackluster (to put it as mildly as I can without being overly impolite).

**Comment by guettli** [comment]
I agree that Stackoverflow is too strict concerning their "no vague question" policy.

**Comment by Tragio** [comment]
@VishwaJay @guettli there's an issue #2523 about this. Instead of creating a Discord/Slack, and have it on the website, docs, Github, and have some moderators (for example, some contributors that helped a lot across the years), we have Gitter that no one uses or like. In this way, instead of we discuss as a community where this project goes and what we should focus on as a community, we have everything going to GitHub Issues that @jgthms don't have time to give it love and keep track of it, neither we have. For me, this seems like a project from @jgthms to himself. I love Bulma and the incredible work that has been done but at the same time is hard to see that the author doesn't seem to want to push this further like Tailwind is being done both with the contributors and the whole team. Just my constructive criticism from the ❤️ to this project and the author.

**Comment by RichardJECooke** [comment]
Does this have an answer yet? Or do I  just keep posting on github issues and bothering the developer :(

**Comment by VishwaJay** [comment]
I think we need to bother the dev, who is trying to move away from the project. My thought is that the project itself (however worthy it might be) is dying due to atrophy.

**Comment by guettli** [comment]
That's life. Things come and go.

**Comment by RichardJECooke** [comment]
Yeah, I realised there really isn't any point to this project anymore anyway. Once you spend a day learning CSS flex and CSS grid there's literally no reason to ever use a grid framework or media-query layout manager ever again.
