### ISSUE TITLE
Bulma.css and editor.js - css not compatible

### ISSUE THREAD

**Issue by kashalkar** [jgthms/bulma#3201]
using bulma together with editor.js causes the editor.js elements like the + icon or the 'click to tune' icon to be shown incorrectly. Everything seems scaled up. 

This is about **Bulma **.

It is a bug.

It is not a browser bug.

### Overview of the problem

This is about the Bulma **CSS framework**

 I'm using Bulma **version** 0.9.1
 My **browser** is: google chrome / safari

I am sure this issue is **not a duplicate**

### Steps to Reproduce

Create an angular project with bulma and editor.js. 
Create a component that shows the editor. Run the app and compare the icons of the editor with how the icons look over here https://editorjs.io/

### Expected behavior
The styling of editor.js should not be overriden by bulma.css

### Actual behavior

Apparently, the styling for the editor is overwritten by bulma.css. Disabling bulma immediately fixes the problem.

**Comment by VishwaJay** [comment]
Compatibility with flexbox seems to be problematic for a lot of packages. And unfortunately, since editor.js has its own CSS which (at first glance) seems block-based, you might try a div wrapper specifically for the editor, set to `style="display:block"` with a unique ID for the editor.

If that doesn't help, and it still breaks, the issue is just one of editor.js's CSS and that of Bulma being incompatible. One package shouldn't have to change solely to accommodate the other.

There are plenty of CSS frameworks out there. And, there are plenty of JS-based editors, too. Fixing the CSS of one might break compatibility with even more others. So, this is one of those cases where "you're on your own" tends to apply.
