### ISSUE TITLE
Input borders have disappeared in the docs

### ISSUE THREAD

**Issue by billylanchantin** [jgthms/bulma#3213]
This is about the Docs.

### Overview of the problem

This is about the Bulma **Docs**

### Description

The borders around the inputs seem to have disappeared. They do appear you hover over the input. 

### Steps to Reproduce

Visit https://bulma.io/documentation/form/general

### Expected behavior

If you visit a snapshot from Nov. 1, 2020

https://web.archive.org/web/20201101041517/https://bulma.io/documentation/form/general/#complete-form-example

you see

![Screenshot_2020-12-10 Form controls(3)](https://user-images.githubusercontent.com/10274508/101790865-ea184600-3ad0-11eb-916d-da2b20ef9ae2.png)

### Actual behavior

If you visit today (Dec 10, 2020 as of submission)

https://bulma.io/documentation/form/general/#complete-form-example

you see

![Screenshot_2020-12-10 Form controls](https://user-images.githubusercontent.com/10274508/101790435-6eb69480-3ad0-11eb-8ada-4b5a5928c3b5.png)

**Comment by msmahon** [comment]
I am experiencing the same issue.

**Comment by lionzeye** [comment]
This seems to be due to order changes in the CSS output, most likely due to the recent sass structure changes:

Old situation:
![image](https://user-images.githubusercontent.com/6161739/101900235-7305af00-3baf-11eb-98c6-ff5d6828c8b7.png)

Current situation:
![image](https://user-images.githubusercontent.com/6161739/101900289-857fe880-3baf-11eb-9b8a-f832f1b438d0.png)

This order change results in the 1px solid transparent border

**Comment by quelchlax** [comment]
I also noticed this today while reading documents on various pages.

**Comment by jenskooij** [comment]
Same applies to select element and file upload element

**Comment by jgthms** [comment]
There is a branch with fixes. Will merge it soon.

**Comment by lionzeye** [comment]
Fixed by @jgthms in https://github.com/jgthms/bulma/pull/3216
