### ISSUE TITLE
Feature: Button radius should be editable trough `$button-radius`

### ISSUE THREAD

**Issue by Morgan-jarry** [jgthms/bulma#3242]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

This is a **Sass** issue: I'm using version [0.9.1]

### Description

Currently, button radius is set with `$radius-small`. If we want to set another radius without editing the `$radius-small` variable, it's not possible.

### Expected behavior

By editing the `$button-radius` variable we should be able to update the default radius button.

### Actual behavior

The `$button-radius` variable doesn't exist for now, so it's impossible to update the radius button without editing `$radius-small`.

**Comment by idolize** [comment]
I noticed this too! And it seems the value in the sass is different from what we see on the docs page? https://bulma.io/documentation/elements/button/

Docs page seems to show a border-radius of `.375em` but the real library is set to `$radius-small` aka `2px` - what gives?

<img width="562" alt="Screen Shot 2021-02-04 at 8 24 29 PM" src="https://user-images.githubusercontent.com/635005/106989420-fdd5d680-6726-11eb-8f69-37d7ed5fd280.png">

Is the docs page just out of date? For what it's worth I prefer the docs style since it appears to also increase/decrease radius based on button size.
