### ISSUE TITLE
Bulma.io docs dark mode

### ISSUE THREAD

**Issue by PixsaOJ** [jgthms/bulma#3611]
This is about **Bulma | the Docs**.

### Overview of the problem

There is an issue created talking about bringing dark mode support for Bulma framework. I basically ask to bring it on website and docs first.

### Description

So I am using Firefox and have extension Dark reader installed. This extension can make websites into dark mode ( has 4 modes ). This extension does not work well for Bulma's docs because colors are affected. Usually in other documentations code is important. It is so annoying to hurt my eyes only on Bulma's website when I code at night. I don't ask to bring dark mode in Bulma as whole, just on website, so I can read docs without burning my eyes. Thank you if anyone does this ❤️ 

Edit: issue is that I want to see accurate light mode colors while using dark mode for website.

**Comment by happycodinghere** [comment]
Here you can find a 100% inverted dark mode (version 0.9.4): https://github.com/jgthms/bulma/issues/3665#issuecomment-1700557591

**Comment by digitigradeit** [comment]
lol, the docs are open-source! and Bulma already supports dark mode using solutions like the one above. If you want the docs to change, feel free to clone locally, update, then submit a pull request. I'm sure @jgthms would be happy to see that.

**Comment by PixsaOJ** [comment]
> lol, the docs are open-source! and Bulma already supports dark mode using solutions like the one above. If you want the docs to change, feel free to clone locally, update, then submit a pull request. I'm sure @jgthms would be happy to see that.

Thank you for responding with "lol" and "host your own docs". However, this is suggestion to  make official Bulma docs website available with dark mode. Unfortunately I can not work on side project right now, that is why I just opened the issue.

**Comment by digitigradeit** [comment]
This isn't really an issue, IMHO.  And you should be opening a bug with the developers of Dark Reader. 

Bulma is a very relevant CSS framework with a large user base. The Dark Reader extension should be more accommodating to (at the very minimum) the top CSS frameworks out there: Bootstrap, Tailwind, Foundation, Bulma, Skeleton, etc.

Let's be clear that you are using an extension that forces stylesheet generalizations for every website that doesn't offer a native dark mode option. I recommend using a better extension like Cascada (macOS/Safari) which allows you to inject your own stylesheet preference, rather than relying on one of the 4 generalization modes. 

Really apologize for how harsh this all sounds, but you're kinda splitting hairs at this point.

**Comment by PixsaOJ** [comment]
It is not an issue, it's a suggestion.

I would still like to see Bulma docs in dark mode despite using any external extensions that do the job(poorly, because they are not designed to invert whole custom design system).

**Comment by digitigradeit** [comment]
Consider disabling Dark Reader for [bulma.io/documentation/](https://bulma.io/documentation/), and using the Firefox extension [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/) as the default mode for this extension has less of an effect on colors than the default option for Dark Reader.

**Comment by PixsaOJ** [comment]
Bulma has dark mode on website now, yay ! 🚀
