### ISSUE TITLE
How is the main menu of bulma.io built? (QUESTION)

### ISSUE THREAD

**Issue by atifc** [jgthms/bulma#3653]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.9.4] 

### Description

How is the bulma.io main menu built? This one:

![image](https://github.com/jgthms/bulma/assets/26510982/8d352e28-48b7-4c29-bb0f-67cedbd98655)

It is responsive, and as the browser window size gets smaller, menu items turn into a dropdown menu behind ellipsis (three dots). 

Is this functionality available in Bulma 0.9.4? I can't find anything about it in the documentation and if this functionality is achievable, I'd appreciate a code sample! Thank you.

**Comment by jgthms** [comment]
Hi. This is not included in Bulma itself because it requires JavaScript. It’s also too specific to be included in the framework. 

However, I can explain how I built it. It’s kind of hacky.

Basically, the JS checks how much space is available for the menu. The JS also renders a clone of the full width menu to figure out what the width is of each menu item. It then figures how many items can fit in the available width and only displays those, and then pushes the other ones in the ellipsis menu.

**Comment by jgthms** [comment]
All the logic is in this function: https://github.com/jgthms/bulma/blob/768ce95d6976a14b526d41024348d8f9692817e9/docs/_javascript/main.js#LL32C28-L32C28

You’ll also notice that this function is called after each viewport resize.
