### ISSUE TITLE
12 columns system not taking full length of container

### ISSUE THREAD

**Issue by idybil** [jgthms/bulma#3743]
This is about the Bulma CSS framework
I'm using Bulma [1.0.0]
My browser is: any

### Overview of the problem

The 12 columns system of version 1.0.0 is not taking the full length of its container like it is in version 0.9.4.

### Description

When using column with is-* and the total of the is-* is 12, the columns container does not take 100% of its parent.

In version 0.9.4, the result look like this: (the red line is the end of the parent container)

![screenshot-001260](https://github.com/jgthms/bulma/assets/2157261/e980b449-0d64-4b14-8250-5bc61411ee12)

In version 1.0.0, the result look like this: (the red line is the end of the parent container)

![screenshot-001261](https://github.com/jgthms/bulma/assets/2157261/9b62374e-5d36-4225-a372-6f6faaace0c0)

In the screenshots above,  we can notice that the width in version 1.0.0 is using a calculation which is not preset in version 0.9.4.

### Expected behavior

Is this a bug in version 1.0.0, or it is intended to be this way ?  Is it possible that the version 1.0.0 have the same behavior as version 0.9.4 ? 

Thanks

**Comment by smileys53** [comment]
Facing the same issue, did you find a solution?

**Comment by idybil** [comment]
@smileys53,  No for now I leave it that way expecting a fix in a future version.

**Comment by SebConejo** [comment]
@idybil I have the same problem. It's quite annoying. I've done some research and this is the trace I'm following:

- If you remove `is-3` on your `column` div, then it works fine. The total width is occupied.
- So I think the problem is linked to the width attached to a column. I see that the `.is-3` class has the following width: `calc(25% - var(--bulma-column-gap) / 2)`. If we replace it with width: 25%, then everything works fine.

It's a bit of a big mistake, and I'm a bit surprised. I'll keep investigating. @jgthms what do you think? do you have any other solutions ?

**Comment by rweverwijk** [comment]
Same issue here with version 1.0.1. Are there any ideas for a solution?

**Comment by SebConejo** [comment]
I'd like to take time to contribute to the project fixing it. I'll try to make a pull-request this week.

**Comment by rweverwijk** [comment]
I think the issue is still valid, but I've used a fixed-grid as a work-around: https://bulma.io/documentation/grid/grid-cells/
