### ISSUE TITLE
Checkbox spacing depends on whitespace

### ISSUE THREAD

**Issue by benjamin-dreux** [jgthms/bulma#3939]
Here is an exemple of what checbox looks without whitespace (in a trimmed html)

![image](https://github.com/user-attachments/assets/5b2d53c4-0684-4655-9016-e384d2def03a)

Here is the code attached to id

<div class="field"><div class="control"><label class="checkbox"><input type="checkbox" name="isOrganization" class="checkbox">Is organization</label></div></div>

But as soon as you create white space arround elements like so

<div class="field">
  <div class="control">
    <label class="checkbox">
      <input type="checkbox" name="isOrganization" class="checkbox">
      Is organization
    </label>
  </div>
</div>

Then checkbox looks as nice as the documentation

![image](https://github.com/user-attachments/assets/aed0b6be-7656-4c32-bfa4-6fee0c8c5f82)

If your html is generated without empty space that not that cool

**Comment by jgthms** [comment]
If you can't alter your HTML, you can add the following in your CSS:

```css
.checkbox > input[type="checkbox"] {
  margin-right: 0.5em;
}
```

**Comment by benjamin-dreux** [comment]
Well I don’t agree that is something users should implement them self.

if we open back this issue I would open a or for this

**Comment by jgthms** [comment]
To force a gap here, whether there's whitespace in the HTML or not, would require turning the .checkbox element into a flex container. This has other consequences. For example, a checkbox with a long text would look different: side by side instead of on single line that wraps. 

I'm not sure I'm ready to impact lots of people for something that hasn't come up in years.
