### ISSUE TITLE
Titles, subtitles significantly smaller in 0.3.0 than previously

### ISSUE THREAD

**Issue by janoluhs** [jgthms/bulma#440]
After updating to 0.3.0 I noticed titles and subtitles are now way smaller than in 0.2.3.

Example: `.subtitle.is-4` or `.title.is-4`, previously sized at `24px`, is considerably smaller for me at the new size of `1.5rem` than it was before. [Image comparing old size to new size](http://i.imgur.com/zAUwXbr.png). 

The new version brings rem sizing; usually `16px` is `1rem`.
However, you set font-size to `14px` not `16px` on the `html` element. Could that be the reason the standard conversion from `24px` = `1.5rem` doesn't hold up?

`24px` divided by `14px` is around `1.71rem` which, when applied, is pretty much the old size. `.title.is-2` is less affected since the difference between the new size `2.75rem` and the calculated size `40px` / `14px` ~= `2.85rem` is less pronounced.

Bug or intentional design decision?

**Comment by hellocosmin** [comment]
Yes, that's the reason, since `rem` units are relative to the body/html base font size.

You can set the body font size to whatever you need, yourself: either override the [$body-size](https://github.com/jgthms/bulma/blob/master/sass/base/generic.sass#L2) variable, or the [$size-6](https://github.com/jgthms/bulma/blob/master/sass/utilities/variables.sass#L37) one.

**Comment by janoluhs** [comment]
Thank you for your clarification!
