### ISSUE TITLE
class "columns" too wide on mobile

### ISSUE THREAD

**Issue by larsvansche** [jgthms/bulma#449]
* [ ] This is about the Bulma **CSS framework**
* [ ] I'm using Bulma **version** [0.2.3]
* [ ] My **browser** is: Google Chrome
* [ ] This is a **Sass** issue: I'm using version [3.4.9]

On mobile, the element with class "columns" is wider than the actual viewport, making the website slightly horizontally scrolling. 
The element is given a negative margin on all sides except the bottom side, and the child element (class="column")

**Comment by goodbytes-gb** [comment]
What do you have wrapped around your `.columns` container?

Bulma's containers are in 'sections' .. If you were to do something like:

```
    <div class="container">
        <div class="columns">
            <div class="column">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor doloribus esse ex expedita minus officiis voluptas. At consequuntur debitis dignissimos eum sed voluptas. Amet assumenda cupiditate earum molestias placeat.
            </div>
        </div>
    </div>
```

It would create a horizontal scroll bar. However if you were to do:

    <div class="section">
        <div class="container">
            <div class="columns">
                <div class="column">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolor doloribus esse ex expedita minus officiis voluptas. At consequuntur debitis dignissimos eum sed voluptas. Amet assumenda cupiditate earum molestias placeat.
                </div>
            </div>
        </div>
    </div>

Then the horizontal scrollbar would be fixed.

See documentation: http://bulma.io/documentation/layout/section/

**Comment by stuartcusackie** [comment]
I'm getting a similar issue. Using a section solves the overlap but adds unwanted padding. If I use CSS to set the section padding back to zero then the overlap comes back. Having a padding of zero on the parent div clashes with the negative margins of the .columns div.

I got around this by overriding the padding on mobile columns like so:

```
.columns {
	margin: 0;
}

@media screen and (min-width: 768px) {

	.columns {
	    margin-left: -0.75rem;
	    margin-right: -0.75rem;
	    margin-top: -0.75rem;
	}

}
```

**Comment by tudoanh** [comment]
Thanks @stuartcusackie, work like a charm.

**Comment by frederikhors** [comment]
Any news on this?

And using this code instead?

```css
@media screen and (max-width: 1024px) {
  .columns {
    margin-left: 0;
    margin-right: 0;
  }
}
```

**Comment by ataul443** [comment]
Thank you so much @stuartcusackie, it really works. You made my day.

**Comment by andre94** [comment]
Thanks @stuartcusackie, I love you 🥇 👍 💯

**Comment by pincheira** [comment]
I'm basically fixing it using @frederikhors's logic, but on the `all.sass`:

```sass
+mobile
  // to fix 'too wide' bug on mobile
  .columns
    margin-left: 0
    margin-right: 0
```

**Comment by EmersonBrSouza** [comment]
This worked fine to me:

`body {
    overflow-x: hidden;
}`

**Comment by mforcer** [comment]
@stuartcusackie The variables didn't work for me unfortunately, any ideas? 

Your original suggestion does work, but not the desired effect for me, I want the container to touch the edge of the viewport... I don't want spacing down either side.

I'm still confused by this issue... it's almost a deal-breaker using Bulma for anyone that cares about their mobile site, is it not? or is it a specific use case?

**Comment by jvitorfrancisco** [comment]
I had the same problem today.

Check if your **.section** does not have **.is-paddingless**.
In my case, that was the problem.

**Comment by babyman** [comment]
I just ran into the same issue and after trying the suggestions above I ended up structuring my page like this:

![image](https://user-images.githubusercontent.com/120736/72076761-12e1fb00-32c4-11ea-8cd1-f172ced6d249.png)

I added `style="padding:0 14px 0 0;"` to the root **section** div, this seems to work in safari and chrome so I'm going to move forward and circle back if I have to.

Some notes:

- adding **.is-paddingless** to the section reintroduced the issue
- including the content in a **container** div limited the width of the page on a widescreen monitor
- `body { overflow-x: hidden; }` and **.is-clipped** left content butted against the screen edge
- modifying the **.columns**  margins also left the page too wide, that might be because I have nested columns...

**Comment by rendaw** [comment]
Same issue.  FWIW the commit that closed this issue was reverted the same day by a subsequent commit so I believe it's no surprise it's not working: https://github.com/jgthms/bulma/commit/f04209dda008f2da058b5f269792facfcb807639

Removing the negative left and right margins in the dev tools fixes the page.  I'm going to open another issue since this is getting no attention.

**Comment by joaopedromattos** [comment]
> This worked fine to me:
> 
> `body { overflow-x: hidden; }`

Works like a charm here! Not a very beautiful workaround, but a smart play, indeed!

**Comment by Lukasiniho** [comment]
I also have the issue! It is still there!

**Comment by danstewart** [comment]
jsfiddle showing the issue:
https://jsfiddle.net/1nfmw0h7/

**Comment by jotaf98** [comment]
Just an update that, predictably, none of the above solutions work anymore, since the exact values are tweaked from time to time.

Except for `overflow-x: hidden`, which is a horrible (but clever) workaround, because it will prevent the user from scrolling in unforeseen situations (and lock out parts of the page).

Wrapping with `.section` adds lots of unwanted space. Functionally, `columns` should "just work" at the top-level, and not introduce space as it's a pure multi-purpose layout building block. I wager that most people start their design with columns, perhaps for navigation items, and (semantic) sections exist inside those columns; it may not make sense to have them outside. So this must be a very common problem, and there's still no good solution in sight.

**Comment by amyhekla** [comment]
Just checking in to say that this is **still** an issue.

**Comment by lxblvs** [comment]
Three years later - still an issue.

**Comment by jotaf98** [comment]
Unfortunately, it's been 8 years in total. 

@jgthms any chance to reconsider this?

**Comment by romanov** [comment]
Is it fixed? I switched to my own columns.
