### ISSUE TITLE
Button stays active after clicking

### ISSUE THREAD

**Issue by d-levin** [jgthms/bulma#482]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.3.1]
My **browser** is: Google Chrome v55.0.2883.95 (64-bit)
I am sure this issue is **not a duplicate**

### Description

<button> elements stay active after clicking them in Chrome (version specified above). This does not happen in Safari (10.0.2) or Firefox (50.1.0). The active state can be removed by clicking somewhere else on the page.

`<button class="button">Click</button>`

It only seems to happen for button elements. Adding the button class to an anchor element (<a>) provides a workaround to the issue.

![](http://i.giphy.com/26gsf4w62qOXz32jC.gif)

### Steps to Reproduce

1. Add `<button class="button">Click</button>` to the page
2. Click the button
3. Observe its state

### Expected behavior

The button should leave the active state when the click event has completed.

### Actual behavior

The button remains in an active state after the click event has completed.

**Comment by yoostk** [comment]
It's rather focused than active, the button has `:focus` pseudo class styling.
It seems Chrome makes buttons focused when they clicked, while others don't.

I made a simple test on this:

![b6fb8e1527ea63feac872c9db9bdcd75](https://cloud.githubusercontent.com/assets/11315660/22163613/d6a90224-df96-11e6-8b3f-c58e03bb32b9.gif)

In safari, clicked button doesn't change it's style, and in chrome it does.

So, I guess it's not just buttons stay focused in Chrome. But they're not focused from the start in other browsers.

Personally, I don't think this issue is something the framework should cope with, because it's browser behavior's difference.

**Comment by mixn** [comment]
This issue doesn’t seem to appear here http://bulma.io/documentation/elements/button/ though — how come it appears when Bulma is used with the same code to generate a button?

**Comment by d-levin** [comment]
Because those aren't actually HTML buttons. They are anchors styled with the button class.

Best,
Dennis
