### ISSUE TITLE
Icons not aligning with text.

### ISSUE THREAD

**Issue by scottzirkel** [jgthms/bulma#484]
Looks like bug from #224 has returned?

![screen shot 2017-01-20 at 19 06 33 pm](https://cloud.githubusercontent.com/assets/1329131/22170487/9774f548-df43-11e6-9902-4a8761d0f0dd.png)

Chrome 55
Bulma 0.3.1
Mac w/ Sierra

```
<p>
    <strong class="is-block">Point of Contact</strong>
    <span class="icon is-small"><i class="fa fa-envelope"></i></span> John Doe
    <br>
    <span class="icon is-small"><i class="fa fa-phone"></i></span> (555) 555-5555
    <br>
    <span class="icon is-small"><i class="fa fa-fax"></i></span> (555) 555-5556
</p>
```

**Comment by jpincas** [comment]
![screen shot 2017-01-26 at 08 56 31](https://cloud.githubusercontent.com/assets/17711012/22323792/6c8f491c-e3a5-11e6-9069-f22fb150fcf1.png)

Same here.

**Comment by MrBrax** [comment]
Started using bulma just a few days ago and this is already a pretty big flaw, if it's not something I've overlooked.

**Comment by jgthms** [comment]
The `vertical-align: top` is there to prevent the `.icon` element to use more space than its height. Otherwise there's a gap below: 
![image](https://cloud.githubusercontent.com/assets/1254808/24333511/f3a66276-1250-11e7-9760-28921877aec8.png)

Solution would be to have a modifier class to remove that alignment on some icons.

**Comment by amir20** [comment]
@jgthms I am guessing I am doing something wrong. But it seems like without `vertical-align` it looks completely broken. 
<img width="141" alt="screen shot 2018-01-26 at 5 47 56 pm" src="https://user-images.githubusercontent.com/260667/35467262-1dd31466-02c1-11e8-958f-6bb206404f8c.png">

Settings `vertical-align: center` makes it better. Not perfect. Is this intended?

**Comment by flyingL123** [comment]
What's the appropriate way to align icons with text? When I place an icon before some text with no modifications, this is the result?

<img width="410" alt="screen shot 2018-03-09 at 11 31 53 am" src="https://user-images.githubusercontent.com/2486712/37218118-85556f16-238d-11e8-9514-5334e9f95ca9.png">


The image above is from the following code:

```
<div class="notification is-warning" v-else>
    <span class="icon is-medium">
        <i class="fas fa-2x fa-exclamation-circle"></i>
    </span>
    This is an warning message.
</div>
```

Adding a `vertical-align: middle;` to the `.icon`, helps a little, but still not perfect:

```
<div class="notification is-warning" v-else>
    <span class="icon is-medium" style="vertical-align:middle;">
        <i class="fas fa-2x fa-exclamation-circle"></i>
    </span>
    This is an warning message.
</div>
```

<img width="352" alt="screen shot 2018-03-09 at 11 31 12 am" src="https://user-images.githubusercontent.com/2486712/37218084-6b79d334-238d-11e8-888e-f4a9c02b7cb7.png">


What is the appropriate way to accomplish this? Should this be the default behavior rather than having to add css to make it work? If it does require custom code, what is the recommended way to get perfect alignment?

**Comment by cyrilchapon** [comment]
Any update on this ?

**Comment by zeiontic** [comment]
broken as shit

**Comment by DavidMay371** [comment]
Hey so for everyone who is encountering this issue, you can just change  ``` display: inline-flex; ``` from the icon class to ``` display: inline-table; ```  or  ``` display: inline-block; ```. Fixed it for me, just add a bit more margin so that it looks nice.

<img width="344" alt="bildschirmfoto 2018-06-03 um 00 23 41" src="https://user-images.githubusercontent.com/11695209/40881368-0fe3a704-66c5-11e8-9c5b-6177323a576e.png">

 ``` display: inline-flex; ``` 

<img width="321" alt="bildschirmfoto 2018-06-03 um 00 23 50" src="https://user-images.githubusercontent.com/11695209/40881369-11be7b6c-66c5-11e8-87aa-0515e3a18ad8.png">

``` display: inline-table; ```

**Comment by AriPal** [comment]
Any update?

**Comment by GopherJ** [comment]
Any update ?

**Comment by scriptcoded** [comment]
See #1858
