### ISSUE TITLE
Add more maintainers?

### ISSUE THREAD

**Issue by ForsakenHarmony** [jgthms/bulma#547]
Maybe you should consider adding some more people who can maintain the project and look after issues and pull requests?

**Comment by jenil** [comment]
Or maybe someone forks it! 😈

**Comment by ForsakenHarmony** [comment]
I mean I could fork it, but what about all the issues and pull requests that exist here

**Comment by ForsakenHarmony** [comment]
@jgthms ?

**Comment by RafaelKeramidas** [comment]
Agreed, the project is popular and well made but the lack of support and updates is a bit frustrating, especially for such a popular repo. There's some good PRs that would be worth merging and issues that can be easily fixed. Forking and grabbing the PRs from here might be a solution but IMO it'd be better to get it fixed here.

Unfortunately my CSS experience is not sufficient for quality contributions or to fork the repo, but I'd be happy to write documentation.

**Comment by ForsakenHarmony** [comment]
Also you'd need a new package on npm if you fork it

**Comment by jenil** [comment]
I agree with @ForsakenHarmony, but then we could rename the project in that case to something like **bulma2**

I am well experienced with CSS and I could fork the repo, but I want to know what are @jgthms's thoughts.

P.S.: Have you'll checked [bulmaswatch](jgog.github.io/bulmaswatch)?

**Comment by mightyiam** [comment]
Doesn't the maintainer have anything to say?

A fork can have any name. And it could have a temporary name, just to get started. For how long are users of this repo feeling a pain of lack of maintenance?

**Comment by ForsakenHarmony** [comment]
The maintainer doesn't seem to be very active on github

**Comment by ForsakenHarmony** [comment]
btw, @jenil that link is treated as relative

**Comment by jenil** [comment]
oops, @ForsakenHarmony updated.

**Comment by vasef** [comment]
Someone should try https://twitter.com/jgthms ?

**Comment by yoostk** [comment]
Looking at [the commit graph](https://github.com/jgthms/bulma/graphs/contributors), I see this project is made of the maintainer's great work. I respect it and I feel the project cannot be done without him.

I understand the frastration comming from the late response. But why don't we just wait for the maintainer's thought about this issue.

**Comment by ForsakenHarmony** [comment]
that's what we're doing

**Comment by jenil** [comment]
I don't think this is happening. Read this https://github.com/jgthms/bulma/issues/556#issuecomment-286894597

**Comment by mib4fun** [comment]
This looks like classic discussion with popular repos and buzy one true god maintainer. ( anyone sailsjs ? )
@jgthms you should bring in more people. Here is my 2 cents, others maintainers could review issues and merge in differents branch or we can gateher a Technical Steering Committee TSC like  nodejs.

I dont think forking is a viable solution... iojs / nodejs or grails / rails. But it definitely help bring maintainer attention :smile:

**Comment by mightyiam** [comment]
Well, latest release demonstrated that the project is indeed active to a degree. Whether this degree is satisfactory to anyone, is for anyone to answer to themselves. One could always use a fork of his own until his issue is figured out upstream. And if ever the single maintainer gets too busy to work on this and enough people care, then we could fork it. I'm staying on board because I love this project.

**Comment by ForsakenHarmony** [comment]
He *should* have read this, so idk what's going on

**Comment by jgthms** [comment]
The community has helped Bulma a lot so far, and I thank all the contributors for that! But finding a maintainer is not an easy task, because _"With great power comes great responsibility"_. 😉 

They would need to share the same philosophy in terms of code and web design, and that is hard to find.

> There's some good PRs that would be worth merging

**Adding features is easy. Maintaining them is the hard part.**

I do review issues and merge PRs that are worth it and follow the guidelines. I simply want to maintain a high quality codebase, by not bloating the project with too much to handle.

It's easy to fix issues, merge PRs, without taking a step back to see if it's worth merging or fixing in the first place. Case in point: #557 was a very thorough PR that was fixing an issue about the delete button. A maintainer would have most probably merged that PR, thinking of helping the community, while in fact the solution was to remove all the Sass functions that this PR was fixing.

I also don't want to penalize the fans of Bulma who liked the framework in the first place because it was modern and lightweight, with only CSS features that are focused on a simple set of styles.

In the end, I don't believe the quality of an open source project is measured by the number of issues closed and of pull requests merged, but rather by how the project is built with an idea of stability and elegance, where every line of code _makes sense_.

I believe fans of Bulma will appreciate this approach.

**Comment by ForsakenHarmony** [comment]
oops

**Comment by ForsakenHarmony** [comment]
You don't necessarily have to add someone with write access, but someone who can review issues and has a way to communicate with you, because getting to you seems hard at times (given this took 10 days)

**Comment by jenil** [comment]
First, we all here know, **Bulma** is turning out to be great. good job @jgthms! 

Second, because the community has helped Bulma get here, they are making efforts to make it better ahead. Yes, finding someone with the same philosophy is difficult but then you have control of it.

Delivering a project with stability and elegance requires more than just adding a label to an issue. Things like roadmaps, participation, comments on PRs, feature updates (_When is the dropdown doing to land in Bulma?_) etc.

The community here is *"your friendly neighborhood"* 😉

**Comment by Technologeek** [comment]
>You don't necessarily have to add someone with write access, but someone who can review issues and has a way to communicate with you, because getting to you seems hard at times (given this took 10 days)

You cannot expect him to work on single issue per given day as he might just keep busy in real life.Moreover, a lot of people seem to have wrong definitions of an open source project.It doesn't necessary  have full participation from the community with submitting PR's.As long as @jgthms is acknowledging the issues and fixing them in the next releases,it's fine.

>Delivering a project with stability and elegance requires more than just adding a label to an issue. Things like roadmaps, participation, comments on PRs, feature updates (When is the dropdown doing to land in Bulma?) etc.  

I disagree.Things like road-maps ,participation  are all subjective.Do you really think this project needs a lot of contributors given that the  owner  is able to solve the issues individually ? You can still support the community by narrowing down a issue which would save owner some time.Also,if you're really concerned about adding new features,you can always fork the code and show us what you came up with.If it's really worth something and appreciated by other users,we can always request owner to add the feature into the main project.

@jgthms  Thanks for the new release,I'm testing the documentation locally!
