### ISSUE TITLE
Feature : Nav Fixed

### ISSUE THREAD

**Issue by dotMastaz** [jgthms/bulma#551]
Hello et bonjour,

tout d'abord, merci beaucoup pour l'excellent travail fourni pour Bulma.io !!

Je souhaite donc réaliser une nav avec position fixed...
Est-ce que je complète le Sass ou tu as prévus quelque chose ?

Merci,
Nicolas

**Comment by dotMastaz** [comment]
No one ? I close ?!

**Comment by woat** [comment]
I think the french is throwing most people off, which is why no one is replying.

But for a quick-fix, I simply took bootstrap's code and it worked.

All you need to do is add this custom class onto your navbar and it will work:
```
    .nav-fixed-top{
        position: fixed;
        right: 0;
        left: 0;
        z-index: 1030;
    }
```

It does also overlay your main content so you will need to add some padding if necessary (bootstrap recommends 70px for their navbar).

([example](https://woat.github.io/fixed-nav/))

**Comment by jgthms** [comment]
Yes I believe a fixed nav can be a tricky one, simply because it involves adding `padding` to the `body`, and having a correct `z-index` for the `nav`.
