### ISSUE TITLE
Columns flex-end and flex-start

### ISSUE THREAD

**Issue by fzingg** [jgthms/bulma#566]
Is there a reason why 

.colums &.is-vcentered
    align-items: center

is implemented and not :

align-items: flex-end
align-items: flex-start

**Comment by jgthms** [comment]
So `flex-start` is the default value.

`flex-end` is almost never used, whereas `center` is a common use case. I didn't want to implement all values anyway, as that would result in just writing CSS in the HTML.

**Comment by Inkeliz** [comment]
I don't know if have some alternative, but `flex-end` seems good for Rigth To Left template, since the columns starts from the right, instead of left.

**Comment by SilencerWeb** [comment]
> flex-end is almost never used

Since when? 🙂

One of the most common block layouts is when an image on one side and content is on another side. Image is absolute since it is an illustration and it doesn't care about the grid. And we need to position the content, it can be on the left or right side. That's where it can be handy, right now we need to add `justify-content: flex-end` manually which isn't really satisfying since it is the work of the grid

**Comment by AurelianSpodarec** [comment]
Yeah. `flex-end` is used a lot... Not sure where you're getting the data from. Every time you want something on the end to the right, you'll want to use `flex-end`. Normally you'd do it with space between or such, but since we're in a grid, would be a good idea to have it.
