### ISSUE TITLE
Fix inconsistency in Titles documentation

### ISSUE THREAD

**Issue by drewmcdowell** [jgthms/bulma#57]
In the Titles section of the documentation, the code preview for titles show each title in a heading tag (h1, h2, h3, etc), but the titles themselves are in paragraph tags.  This seems misleading as it doesn't properly illustrate the margins, etc. that result from using actual heading tags.

**Comment by jgthms** [comment]
The markup should have no effect on the rendering of these titles. The code shows heading tags because that's how people are probably gonna use it, but the website's markup needs paragraphs in order to avoid polluting the hierarchy.

Also, this issue is for the website itself: https://github.com/jgthms/bulma-website
