### ISSUE TITLE
0.4.0 .select with .is-loading

### ISSUE THREAD

**Issue by nodtem66** [jgthms/bulma#584]
### Overview of the problem
This is about the Bulma **CSS framework**

### Description
when use `is-loading` with `.select`, the loading spinner is overlapped with drop-down triangle

### Steps to Reproduce
```html
<div class="field">
  <div class="control is-loading">
    <span class="select">
       <select>
          <option>-- add new --</option>
       </select>
    </span>
  </div>
</div>
```
[Codepen](https://codepen.io/nodtem66/pen/yMvwgX)

### Expected behavior
![2](https://cloud.githubusercontent.com/assets/220425/24134054/4dc75736-0e34-11e7-8ac3-d750b76c07a7.png)

### Actual behavior
![1](https://cloud.githubusercontent.com/assets/220425/24134046/4914d5ec-0e34-11e7-9a53-aa6682e173ab.png)

**Comment by jgthms** [comment]
That is the expected behavior, as it's the select that is loading.

**Comment by adambiggs** [comment]
I would love to see this re-opened.

The current behaviour isn't consistent with input/textarea/button loading state. In all those cases, the loading spinner appears inside the control.

But currently select input loading state places the spinner outside the control, aligned to the right of the page. In most cases the user won't even notice the spinner because on wide pages it's displayed very far away from the relevant control...

The fix outlined in @nodtem66's Codepen link seems like a massive improvement.

**Comment by jgthms** [comment]
I misunderstood. LMFT.

**Comment by adambiggs** [comment]
Nice, thanks @jgthms!

FYI I fixed it easily in my app with the following:

```sass
@import "~bulma/bulma"
.select.is-loading
  @extend .control.is-loading
  &:after
    top: 1em
```
