### ISSUE TITLE
Don't forget about RTL direction please

### ISSUE THREAD

**Issue by elkebirmed** [jgthms/bulma#6]

**Comment by jgthms** [comment]
I don't have any experience in implementing RTL in CSS, but I'd be glad if you could help us out.

**Comment by elkebirmed** [comment]
I'll try

**Comment by msikma** [comment]
When using as much of flexbox's features as possible, and no attributes with "left" or "right" in it, most stuff will "just work". But for example, right now the grid system contains `margin-left` for spacing, which breaks RTL. This would need to be replaced with an equal margin on the left and right sides. That's one example.

**Comment by elkebirmed** [comment]
It's a great idea @msikma

**Comment by msikma** [comment]
It's definitely a bit of work to get RTL working correctly but I think it shouldn't be too bad. 😀

For example, for the columns, if you give every column `margin-left: 10px; margin-right: 10px;` and then modify the `.columns` class to have `margin-left: -10px; margin-right: -10px;`, it will work fine on an RTL layout:

![image](https://cloud.githubusercontent.com/assets/1507745/12779678/9fcec128-ca69-11e5-9246-55810899f299.png)

This is best done sooner rather than later since this *will* break people who have built complex site designs on top of the grid system as it currently is.

**Comment by mohamadnorouzi20** [comment]
If you want to implement RTL please use conditionals in code instead of using a npm tool.

**Comment by msikma** [comment]
Could you explain what you mean by npm tool or conditionals? I'm not entirely sure what you mean. In my idea there should be a single codebase that works for `dir="ltr"` and `dir="rtl"` without any other need for setup, which should not be too hard to do.

**Comment by mohamadnorouzi20** [comment]
@msikma This is an npm tool for example: https://github.com/MohammadYounes/rtlcss
and by conditionals I mean using **if statements**.

**Comment by mohamadnorouzi20** [comment]
@msikma **Semantic UI**(a giant framework) for example uses npm rtl packages instead of using conditionals in css preprocessor.

**Comment by msikma** [comment]
I don't think there's a need for conditionals at all. It's perfectly possible (in fact, beneficial) for a CSS framework to support LTR and RTL at the same time, and even without overrides or selectors that include `html[dir="rtl"]`. This also means dynamic websites could switch between an LTR and RTL language without reloading a different CSS file.

The trick is (mostly) making sure not to use any styling that explicitly favors left or right.

**Comment by ShaggyDude** [comment]
"The trick is (mostly) making sure not to use any styling that explicitly favors left or right." Seems like a pretty big trick.  Semantic UI is awesome. almost good enough for me to switch to less. I'm hoping this project will surpass it.. Let me know if I can help out...

**Comment by ahmadalukah** [comment]
you can include a a java script code that convert every "left" in the class to "right" , and every "right" to "left" . and adding `direction: rtl;` in the body.. I guess that will make almost everything ok.

**Comment by jens1o** [comment]
But that isn't a js framework.

**Comment by ahmadalukah** [comment]
I know, it just could be a simple and fast solution for those who want an RTL version :smile:

**Comment by ImanMh** [comment]
should be able to set offsets from right

**Comment by zaidakram** [comment]
Any progress on this front?

**Comment by mohammadrafigh** [comment]
I implemented this feature and will send PR when I tested everything.

**Comment by spacemudd** [comment]
#889 - I made a new fork ready for merge with rtl support. It doesn't force bad rtl methods (changing 'right' to 'left' keywords and vice versa) without proper logic. It uses a mixin =rtl for the style that would be used in rtl pages.

I believe this is an elegant solution with proper customization.

**Comment by mohammadrafigh** [comment]
here is my fork you can use it by npm install bulma-rtl currently you can use it with sass modules only give me a few hours and I will update this fork with latest bulma changes and I may send another PR with a different approach. otherwise if the Bulma repo maintainers don't want to merge this PR then you can use bulma-rtl from tomorrow and so on... I try to fix rtl related issues there. let me know your thoughts. also I may do some tweaks and add some custom components later if I have time.

https://github.com/mohammadrafigh/bulma-rtl

P.S. if repo maintainers decide to use my approach I will un-publish bulma-rtl. I just did it to help others like me waiting from 2016 till now.

**Comment by mrjk990** [comment]
@mohammadrafigh need a new bulma rtl for 0.6 version , plzzzz

**Comment by mohammadrafigh** [comment]
@mrjk990 I will do it tonight. but please make issues for this requests on the RTL repo thanks.

**Comment by mrjk990** [comment]
@mohammadrafigh ok i'll

**Comment by mohammadrafigh** [comment]
@mrjk990 I updated the repo to 0.6.1 here is the link I mentioned above:

https://github.com/mohammadrafigh/bulma-rtl

you can use bulma-rtl as package name to install it.

**Comment by mrjk990** [comment]
@mohammadrafigh  thank you bro :kissing_heart:

**Comment by kodeine** [comment]
Any idea why this is not added into Bulma core?

**Comment by spacemudd** [comment]
@kodeine The method of having a separate file `rtl.css` is cumbersome, hacky, and requires a ton of _changing_ the original code. It's an old method because we didn't have css pre-processors.

I once created a PR for utilizing [dir=rtl]. The fork is still up https://github.com/spacemudd/is-rtl-bulma with a readme.md describing how I want to go about it. I didn't dive into it because at that time Bulma was undergoing major changes.

I really believe that's the optimal solution because:

- Doesn't interfere at all with the source code. 
- Less than 20kb increase in size.  If `$is-rtl` is set to true.
- Makes proper use of [dir=rtl] something of which MANY rtl-developers seem to never get.

I think I'll spend a couple more hours updating the repo.

**Comment by mohammadrafigh** [comment]
@spacemudd this approach won't work in bidi context, i.e. [dir=auto]

**Comment by spacemudd** [comment]
@mohammadrafigh As far as I know, `[dir=auto]` sets the direction based on what kind of the first letter is. (A letter from rtl or ltr language?) - https://codepen.io/anon/pen/vjebJy

If multi-directional-language posts are a common occurrence in one's application, I would go about having a css class that strictly specify the direction. I fail to see where the problem in that though.

**Comment by mrg0lden** [comment]
@spacemudd I really see `[dir=auto]` as the silver bullet of bi-di problems, only some bulma components needs specified direction adjustments, such as `.is-loading` and `.column.is-offset-x`.

For futuristic browsers support only, see: https://developer.mozilla.org/en-US/docs/Web/CSS/:dir

**Comment by Rux77** [comment]
I have read about [CSS Logical Properties and Values](https://drafts.csswg.org/css-logical/), which I think is THE solution for all RTL problems. Its already [been supported in all major browsers](https://caniuse.com/#feat=css-logical-props) except for MS ( which they plan to implement it as it stated [here ](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/7438435-css-logical-properties) - the response was in 2015 so who knows when they will start! ). Other than this, I don't see any better solution than having a separate `rtl.css` file.

**Comment by Rux77** [comment]
Ok, huge news!

MS is [currently being rebuilt as a Chromium-based browser](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/).  Which means, we can expect all features and functionality of other Chromium-powered browsers brought to Edge!! so, **CSS Logical Properties and Values** is coming in 2019!

**Comment by mrg0lden** [comment]
@Rux77 Great! But I think IE is still a problem. I wish it support get dropped soon. People should learn to adapt, and we should help them as well.

**Comment by Rux77** [comment]
I think that Bulma should not be focused to support old browsers like IE. Bulma should always support modern technologies and modern browsers. If someone wants the support of older browsers should use bootstrap or something else. 

As for IE browser being dropped, I don't think MS will do such action, at least not in the near future.

**Comment by mrg0lden** [comment]
Since this issue isn't getting any love, I decided to start doing something useful by listing all Bulma features that are RTL incompatible and how it should be.

I'll update this list with time, feel free to contact if you want to help in doing this list.

## Navbar
* `.navbar-start` have `margin-right: auto` which pushes the element toward the left. To fix this it should have `margin-right: unset` and `margin-left: auto` or can be resolved by logical properties.
* `.navbar-burger` have `margin-left: auto` which pushes the element toward the right.

##Button

* `.buttons` have `padding-right: .5rem` for `.button:not(:last-child):not(.is-fullwidth)`

## Input

* `.is-loading` adds the icon on the right side

**Comment by omrllm** [comment]
Hey guys,

I have seen that styling the body like this:

```css
body.ar {
direction: rtl;
}

```

works very well, except for the navbar.

Anyone else getting the same result?

The navbar gets weird, instead of being like this but in the opposite direction:

![Screenshot from 2019-03-26 22-15-16](https://user-images.githubusercontent.com/45340167/55034124-0a5e5380-5015-11e9-91c1-2752c4ccb954.png)

&

![Screenshot from 2019-03-26 22-15-27](https://user-images.githubusercontent.com/45340167/55034146-14805200-5015-11e9-92da-b89b4c2d04d5.png)

It acts like this:

![Screenshot from 2019-03-26 22-13-53](https://user-images.githubusercontent.com/45340167/55034191-2b26a900-5015-11e9-96bf-a690f52866bd.png)

&

![Screenshot from 2019-03-26 22-14-33](https://user-images.githubusercontent.com/45340167/55034196-324db700-5015-11e9-918a-ea1c358138cf.png)


### Possible answer

I have seen this answer on Stackoverflow:

> Well, i have solved it by digging a bit in the code and understanding what should be changed in oreder for it to work properly as RTL navbar.
> 
> We have three main sections in the navbar, and i recommend making a class for it in you app.css or whatever name you have for your css called rtl-navbar and apply it on navbar-burger, navbar-end. on top of this, you should apply direction:rtl on the main navbar container.
> 
> ```css
> .navbar-rtl{
>    margin-right: auto;
>    margin-left: 0;
> }
> ```

But it doesn't work.. maybe because I'm not the doing the right steps.

Could anyone try this approach or something easy and similar?

**Comment by mrg0lden** [comment]
@omrllm If you're using npm then install this

It's a WIP based on logical props  (note that it's not supported in edge nor Internet Explorer).

https://github.com/mrg0lden/bulma/tree/temp
`npm i https://github.com/mrg0lden/bulma.git#temp`
or 
`yarn add https://github.com/mrg0lden/bulma.git#temp`

**Comment by omrllm** [comment]
@mrg0lden 

Nah, I'm not; I'm using the CDN.

**Comment by yazeed** [comment]
Check this guide for a proper RTL implementation
https://www.rtlstyling.com/

**Comment by jgthms** [comment]
I just opened a PR: #2882 
I'll probably merge and release it soon.

**Comment by mohammadrafigh** [comment]
Thanks @jgthms, So I will mark my fork at https://github.com/mohammadrafigh/bulma-rtl as deprecated and will remove the package from npm soon.

**Comment by jgthms** [comment]
Thank you @mohammadrafigh for supporting RTL all this time! I think with the popularity of CSS logical properties, Bulma is ready to support RTL.

I'd be interested to know your thoughts on my implementation of RTL, and if anything can be improved.

**Comment by mohammadrafigh** [comment]
@jgthms my pleasure. I had a look at PR and now I see it's going to be in the right direction. It's perfect. Yes css logical properties are great.

**Comment by Tovli** [comment]
Hi
Is there a plan to resolve this issue?

**Comment by mas-iota** [comment]
Any update on this?

**Comment by blue-range** [comment]
I think we should use start/end instead of left/right. it makes more sense specially in flexbox concept

**Comment by mohammadrafigh** [comment]
I definitely agree with you. All major browsers are supporting
*-inline-start and *-inline-end. This will make things a lot easier.
