### ISSUE TITLE
What is the best way to create an administration template ?

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#646]
Hi,

I'm asking myself what is the best way to create a classic Administration theme using bulma ?
The goal is to have:
- 1 top nav bar
- one left menu (full-height)
- 1 content area

Like the example on this screenshot
<img width="1440" alt="screen shot 2017-04-06 at 20 28 49" src="https://cloud.githubusercontent.com/assets/24766179/24769694/b3bd9962-1b07-11e7-8942-956809d2a20b.png">

Can you please give me your opinion about the 2 ways below:

1. Create **one root full-height hero** with **hero-head including nav component** and **hero-body including 2 columns** (one for the left administration multi-level menu including the Menu component and one column for the content)

2. Add **Nav component as first root element** and **2 columns as second root component** (one for the left administration multi-level menu including the Menu component and one column for the content) 

Don't hesitate to propose other option or improvement.

Kind regards

**Comment by kureikain** [comment]
Here is my own opinion.

When I take a step back, and look at these kind of dashboard, they are very bloated to me. At first place, the reason I use Bulma because I feel it is simple enough to get started without bloating thing that I rarely use(I know I can select individual component but still).

So I tried to go with a minimal design for dashboard. I found a good example of dashboard design is DigitalOcean. Their dashboard is very clean and get expose per step instead of bloating it with everything.

This is how I designed my dashboard[1]

https://assets.noty.im/assets/bg/shot-home-b9ce700e3c17c42e6795b0d6e4ad48178a5a24bbcb79e14749fa8429792956bc.jpg

I have a top navigation. And each page sections may or may not have its own `horizontal` sub navigation like bulna docs.

I opts for this design because I think when using `horizontal menu`, it limits my space and makes me thing about what I can put in there with only some core things.

---

[1]: https://noty.im

**Comment by Wikiki** [comment]
Hi @kureikain,

thank you for your feedback. I agree with you about the simplicity and I really like your design. But my concern is : what about an application which can handle a lot of modules, then a lot of root links into the menu ? I'm afraid that in this way there is not enough space on top (even by splitting them into root links and sublinks).

Regards,

**Comment by IlanF** [comment]
The most basic dashboard layout could be something like this:
```
<nav class="nav">
  <!-- top nav menu -->
</nav>
<div class="section">
  <div class="columns">
    <aside class="column is-2">
      <nav class="menu">
        <!-- sidebar menu -->
      </nav>
    </aside>
    <main class="column">
      <!-- main content area -->
    </main>
  </div>
</div>
```
[Here is a full example](https://codepen.io/ilanf/full/ybNVwg/)

The menu is not full height but can be with some CSS tweaks, same with the main content area.

**Comment by Wikiki** [comment]
Hi @IlanF

Thank you for this simple layout and the example.

Why using a hero for the top navbar ?

Regards

**Comment by IlanF** [comment]
No particular reason, I just liked the way it looked better...
You can remove the .hero and only use the .nav if you don't intend to use the hero-title/subtitle / colors.

**Comment by Wikiki** [comment]
Thanks for your feedback.

**Comment by Wikiki** [comment]
Up

Do you know how to create a **full-height** template :
- Fix top navbar
- Side menubar with vertical scroll
- Right page content with independent scroll

Regards

**Comment by Wikiki** [comment]
We are proud to announce the first premium administration template on CreativeBulma :-D.
try it at: https://demo.creativebulma.net/hexalight
