### ISSUE TITLE
file dialog input request

### ISSUE THREAD

**Issue by faststare** [jgthms/bulma#675]
please kindly support file dialog for opening and saving file/s.
tia

**Comment by Technologeek** [comment]
Could be a nice feature add-on.It is fairy easy if you can just inherit the properties of the button.Although it is not recommended to do so (maybe due to incompatibility with the browsers ),I did a small fix for you if you're looking to use it right away in your project and not wait for the official release of the feature. Check it out here : [Codepen](http://codepen.io/Technologeek/pen/oZGPYG)

**Comment by chintanbanugaria** [comment]
Here's my workaround for File Input
[https://jsfiddle.net/chintanbanugaria/uzva5byy/](https://jsfiddle.net/chintanbanugaria/uzva5byy/)

**Comment by jgthms** [comment]
Dupe

**Comment by faststare** [comment]
sorry guys. they doesn't work. I still received an error message with file not found.
