### ISSUE TITLE
Customization for n00bs

### ISSUE THREAD

**Issue by Musmula** [jgthms/bulma#698]
### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.4.1]

I am sure this issue is **not a duplicate**

### Description

I'm still pretty new to Bulma so when I tried following the short customization example I ended up bashing my head against the invert of the primary color. When I chewed through the paragraphs I didn't pay much attention to the fact that `$blue` is a predefined color and therefore has a `$blue-invert` counterpart. 

If you're setting this light of a pink as the new primary, maybe it's worth explaining that if you want the text on it to be more legible, you need to import the `"../bulma/sass/utilities/functions"` file and then define

```sass
$pink-invert: findColorInvert($pink)
$primary-invert: $pink-invert
```

There's nothing ***wrong*** with the docs, but for a newb, the sentence 
> Notice how the $blue-invert is now black instead of white, based on findColorInvert(#72d0eb)

means absolutely nothing

**Comment by jgthms** [comment]
Fair enough.

Yeah, in the case of how `$blue-invert is now black instead of white`, it's because `$blue-invert` is already set to `findColorInvert($blue)`. So updating `$blue` will update `$blue-invert`.

The `findColorInvert()` function is here to remove the need to set the invert colors **manually**. It's calculated based on the luminance.

It's also possible to set `$primary-invert: #fff` if the user feels it's the correct color.

I'll try to add more explanations.

**Comment by Musmula** [comment]
Awesome, thanks

**Comment by Musmula** [comment]
Awesome, thanks
