### ISSUE TITLE
Dropdown doesn't support icons

### ISSUE THREAD

**Issue by roosmaa** [jgthms/bulma#702]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.4.1**
My **browser** is: Google Chrome 57.0.2987.133 (64-bit) OSX

### Description

It looks like the `<select>` element doesn't support field icons as other `<input>` based elements. Would be nice if it did.

### Steps to Reproduce

```html
<div class="field">
  <p class="control has-icons-left">
    <span class="select">
      <select>
        <option value="" disabled selected>Country</option>
        <option>Select dropdown</option>
        <option>With options</option>
      </select>
    </span>
    <span class="icon is-small is-left">
      <i class="fa fa-globe"></i>
    </span>
  </p>
</div>
```

### Expected behavior

<img width="231" alt="screenshot 2017-04-24 12 04 58" src="https://cloud.githubusercontent.com/assets/65596/25332316/4097964e-28e6-11e7-8695-6d5f78b9c991.png">

With workaround of `<select style="padding-left: 2.25em">`

### Actual behavior

<img width="204" alt="screenshot 2017-04-24 12 02 46" src="https://cloud.githubusercontent.com/assets/65596/25332292/24c3baa6-28e6-11e7-8a87-01c2c32050e9.png">

**Comment by marc-mrt** [comment]
Hello !

I encountered this problem not long ago, but the result I was looking for is a bit different:
Instead of having an icon for the entire <select /> dropdown, I wanted to have an icon associated to each <option /> inside the dropdown menu.

The thing is I don't know if this is a thing people actually do and/or seek in bulma.
Take it as a suggestion 👍

**Comment by ANorseDude** [comment]
... so is this fixed or?
