### ISSUE TITLE
[Bug] "help" class behaviour in horizontal form "is-grouped" field

### ISSUE THREAD

**Issue by tu5** [jgthms/bulma#715]
Bug, Bulma 0.4.1.

Helper text should display below form, not on the right.

![image](https://cloud.githubusercontent.com/assets/18059922/25423665/da324be8-2a65-11e7-84cb-708f42d18bb9.png)

https://codepen.io/anon/pen/pPNMVj

**Comment by FrancoisH** [comment]
I can confirm this. I ran into the same issue.

**Comment by trixn86** [comment]
I experienced the same. The example is the docs for combined usage of `is-horizontal` and `is-grouped` is misleading because it uses a `<div class="field is-grouped">` inside the code example that only has one `<p class="control">` in it which basically makes `is-grouped` useless. 

Additionally in my opinion it is best to use a help text as a `<span>` inside the `<p class="control">`wrapper to make sure it will always be displayed below the input and not right to it if used with `is-grouped` because this would display every paragraph (including `<p class="help"></p>`) next to each other as noted in the [above comment](https://github.com/jgthms/bulma/issues/715#issue-224375077) from @tu5. 

**The currently suggested way to display help text does not work together with `is-grouped`.**

I suggest to edit the code example in the docs like this:
```diff
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">From</label>
  </div>
  <div class="field-body">
    <div class="field is-grouped">

      <p class="control is-expanded has-icons-left">
        <input class="input is-danger" type="text" placeholder="Name">
        <span class="icon is-small is-left">
          <i class="fa fa-user"></i>
        </span>
+       <span class="help is-danger">This is a help text.</span>
      </p>

+     <p class="control is-expanded has-icons-left has-icons-right">
+       <input class="input is-success" type="email" placeholder="Email" value="alex@smith.com">
+       <span class="icon is-small is-left">
+         <i class="fa fa-envelope"></i>
+       </span>
+       <span class="icon is-small is-right">
+         <i class="fa fa-check"></i>
+       </span>
+       <span class="help is-success">This is a help text.</span>
+     </p>
    </div>
-    <div class="field">
-      <p class="control is-expanded has-icons-left has-icons-right">
-        <input class="input is-success" type="email" placeholder="Email" value="alex@smith.com">
-        <span class="icon is-small is-left">
-          <i class="fa fa-envelope"></i>
-        </span>
-        <span class="icon is-small is-right">
-          <i class="fa fa-check"></i>
-        </span>
-      </p>
-      <p class="help is-success">This email is correct</p>
-    </div>
  </div>
</div>
```
It looks like this:

<img width="1680" alt="is-horizontal and is-grouped combined usage" src="https://user-images.githubusercontent.com/20125507/28241105-00298688-698e-11e7-9248-3ee342dd3a43.png">

This code example in a [codepen](https://codepen.io/anon/pen/mwoZaQ).

Another "issue" is that the label on the left is unnecessarily padded on it's left side. Ideally the container should be as wide as the widest label in the form.

**Comment by trixn86** [comment]
I can't see how that fixes any of the above problems. The help text will still be aligned in the same flex row appearing next to the input field instead of below it if you use it in a `<p>` as a sibling of the `<p class="control">` as the docs suggest. Why not suggest to use the `help` class on a `<span>` inside the `<p class="control">`? Also in my point of view the example for using `is-grouped` in a horizontal form is even less informative.
