### ISSUE TITLE
How do you override variables?

### ISSUE THREAD

**Issue by JTallis** [jgthms/bulma#734]
I'm struggling to override variables. The following works (except for $white and other variables being undefined):

```scss
@import "node_modules/bulma/sass/utilities/functions.sass";

$epo-blue: #1884BC;

$body-background: #1E2124;

$primary: $epo-blue;

$text: $white;
$text-strong: $white;
```
I wanted to enable such variables so I changed the import to `@import "node_modules/bulma/sass/utilities/_all.sass";` and now my variable changes are not recognised.

The following, however, works:

```scss
$epo-blue: #1884BC;

$body-background: #1E2124;

$primary: $epo-blue;

// Import Bulma's initial variables
@import "node_modules/bulma/sass/utilities/_all.sass";

$text: $white;
$text-strong: $white;
```

So I'm curious on what is the correct way to overriding variables?

**Comment by jgthms** [comment]
Check out http://bulma.io/documentation/overview/customize/

**Comment by JTallis** [comment]
I was looking everywhere and overlooked that! Apologies.

**Comment by GerritMaatkamp** [comment]
This doesn't work. I installed node-sass and bulma and bulma is getting on my nerves. The only way I can even use my own classes is by putting !important after stuff. What the heck! I wrote my classes with Dutch names just to be sure there is nothing in Bulma that is the same. And this method you tell me about doesn't work because my terminal tells me it can't find the files. even though the path is absolutely correct and the files are there. It would be great to see a step by step setup or something.

**Comment by GerritMaatkamp** [comment]
https://bulma.io/documentation/customize/with-node-sass/

New docs seem to be better. 
Sorry for not updating, I previously also managed to fix it, if it doesn't work give a little more details on your situation and I'll try to help out.
