### ISSUE TITLE
[Feature Request]: Add a Carousel/Slideshow Component to Bulma 0.4.X

### ISSUE THREAD

**Issue by thecodechef** [jgthms/bulma#775]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.4.2]
My **browser** is: firefox

### Description

It  would be nice to have a carousel component to use for image sliders

### Bulma Carousel Example

```
<div class="slides">
  <ol class="slide-indicators">
    <li class="is-active"></li>
    <li></li>
    <li></li>
  </ol>
  <div class="slide-item is-active">
    <img class="slide-image" src="..." alt="Slide 1">
    <p class="slide-caption">Slide 1</p>
  </div>
  <div class="slide-item">
    <img class="slide-image" src="..." alt="Slide 2">
    <p class="slide-caption">Slide 2</p>
  </div>
  <div class="slide-item">
    <img class="slide-image" src="..." alt="Slide 3">
    <p class="slide-caption">Slide 3</p>
  </div>
  <div class="slide-controls">
    <p class="icon slide-prev is-large">
      <i class="fa fa-chevron-left"></i>
    </p>
    <p class="icon slide-next is-large">
      <i class="fa fa-chevron-right"></i>
    </p>
  </div>
</div>
```

**Comment by jgthms** [comment]
It would require JavaScript, which Bulma doesn't provide.

**Comment by thecodechef** [comment]
Actually all i was talking about was adding the css only. but ok thanks for letting me know

**Comment by VizuaaLOG** [comment]
Problem with this I think is that in order for it to look 'right' it would need JS. Otherwise you'll just have a list of images. Also, there isn't really that much to style with a carousel in my opinion. 

_Sent from my Htc HTC 10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jgthms** [comment]
Sorry @thecodechef for my previous reply. I realise it was quite abrupt.

To answer more thoroughly why I don't think it's a good addition to Bulma, is that for a carousel to work well, it needs perfect interaction, which will define the markup (and not the other way around).

Also, most carousels update the DOM with JavaScript, so the initial markup is only there as an API for the plugin.

I recommend [Flickity](https://flickity.metafizzy.co/) in any case.

**Comment by LaundroMat** [comment]
I'm not having any luck integrating flickity with bulma.io... Does anyone have a working example?

Compare [this codepen](https://codepen.io/Laundro/pen/wyWrJx) with [one without importing bulma css](https://codepen.io/Laundro/pen/qxNPXq). I'm not enough versed in CSS to know where the problem lies...

**Comment by Raptor121-SA** [comment]
Give this a try https://bulma.io/extensions/

**Comment by joakim-tldr** [comment]
> It would require JavaScript, which Bulma doesn't provide.

flexbox, overscroll-behavior, scroll-snap-type and scroll-behavior.
