### ISSUE TITLE
Switch to CSS Grid?

### ISSUE THREAD

**Issue by travisfisher** [jgthms/bulma#813]
What is the project's plan as it pertains to css-grid (https://developer.mozilla.org/en-US/docs/Web/CSS/grid)?

Support (http://caniuse.com/#search=css-grid), as it stands today, is pretty solid and it seems to fit in with the cutting edge stance that Bulma took with using Flexbox.

**Comment by werthen** [comment]
I actually was thinking about this today as well, but we must keep in mind that flexbox as it stands covers 97% of users, while the CSS grids only covers 67% or so

**Comment by jgthms** [comment]
CSS Grid is planned but will not replace Flexbox as they serve different purposes.

**Comment by nathanieldavis** [comment]
Yeah, wondering what the status of CSS grid support is now that some time has passed!

**Comment by PayteR** [comment]
So... it's almost 2 years since this issue has been opened, any news regarding this?

And what's the reason to not switch from flexbox to CSS grid in columns? I think about just one - it's not possible to set auto width to fill space. But pros are global gap with no need to hack negative margins, "spans" are super easy and stretched row is by default.

**Comment by evdama** [comment]
@jgthms I've looked around in the issues and online but couldn't find any clear statements on the current CSS grid status with bulma. Can you share some thoughts maybe?

**Comment by neutraladvocate** [comment]
now its another year? Any answer to CCS Grid adoption
