### ISSUE TITLE
Comparison to Bootstrap

### ISSUE THREAD

**Issue by brianmhunt** [jgthms/bulma#82]
It'd be really valuable to see a comparison of Bulma to Bootstrap, and/or a transition guide, since a lot of folks that are target consumers of Bulma probably use Bootstrap.

It'd also be neat to know what issues one would encounter if using both concurrently – during a transition period.

Cheers.

**Comment by ibrahimyu** [comment]
If we try to compare, Bulma doesn't have Javascript components (at least right now) so things like accordion, slideshow/carousel, are still missing.

AFAIK all the class names are different from Bootstrap, so I assume the only issue if using both is redundancy.

**Comment by brianmhunt** [comment]
It would help to have a list of things that are not present as well.  That information is also useful.

The guide would really be:

1. what's in BS but not Bulma; 
2. how things present in both are done different; and
3. what's in Bulma but not BS.

**Comment by steveoc64** [comment]
> Bulma doesn't have Javascript components (at least right now) 

It would be nice if this feature remained that way.

One of the attractions with Bulma at the moment is that it does one thing only, and does it well. There are enough frameworks out there that try to be more than that .... and there is usually a longer term cost associated with that approach.

It would be ideal (in my opinion) if any extras that required JS could be spun off into an optional add-in package.  We all tend to have our own weird and wonderful ways of coding behavior into our apps, and the options for doing so grow daily.  (plain old JS, jquery,  React, Angular,  ... and now we have some cool transpilers to play with as well)

In my case, Im trying to keep 100% of my frontend written in Go, so Im deliberately avoiding pulling in any JS libs if I can help it.

**Comment by 3noch** [comment]
:+1: @steveoc64

In my case I'm using Haskell for the front-end.

**Comment by brianmhunt** [comment]
FWIW, Bulma is particularly interesting for me because its JS-agnosticism lets it pair well with Knockout.

**Comment by jgthms** [comment]
@steveoc64 
> Im trying to keep 100% of my frontend written in Go

What do you use exactly? I'm interested.

@3noch 
> In my case I'm using Haskell for the front-end.

Same question :smile:

**Comment by 3noch** [comment]
@jgthms It's an FRP system called Reflex-DOM (think Elm + power - polish): https://obsidian.systems/reflex-nyhug/

**Comment by steveoc64** [comment]
Sorry for the thread derail ;)

In my use case, Im using Go at the backend and GopherJS at the front end (which compiles to JS)

Its not without its issues, but its a great fit for this particular project. Its a control app for heavy machinery, so security fails can lead to nasty and expensive surprises. The less free flowing JS at the front, the better.

In this case, most things are run from the backend. After an initial boot up with minimal HTML, the front end switches over to secure websockets, and uses bidirectional RPC calls to and from the backend. (no HTTP) 

The front then receives little packets of instructions from the backend that once decoded contain a view template, a data model, and some logic to be executed.

So in this case its more about maintaining control, and making it really hard for anything at the frontend to be able to subvert or otherwise break out of that control.  

CSS markup is fine, but Id rather not have anything else executing at the front end that is outside of those logic packets that the backend is issuing to authenticated connections on a strictly as-need basis.

Bulma is a great fit in this case, because it just manages the display markup, and doesnt try to get too smart beyond that.

PS: Transpiled Haskell sounds great too. A real type system !
