### ISSUE TITLE
Feature Request: is-shadowless modifier

### ISSUE THREAD

**Issue by connectkushal** [jgthms/bulma#934]
Just like `is-radiusless` and similar modifiers, is it possible to have an `is-shadowless` modifier ?

A particular use case would be with the box class. Some other uses may be in forms or dropdowns.

**Comment by connectkushal** [comment]
Im facing this issue #929  when i tried to work on this

**Comment by Wikiki** [comment]
Hi,

for th issue #929 there is already the variable box-shadow available (called $box-shadow & $card-shadow)

Unfortunately box and card don't have border rules defined.
I wanted to integrate it but @jgthms told me it could break some components. That's why I have created the current issue. (see Box: Fix missing variables #924)

Regards

**Comment by connectkushal** [comment]
@Wikiki ok. Thanx for the info and the plugins :)
