### ISSUE TITLE
Plugin development.

### ISSUE THREAD

**Issue by rajibahmed** [jgthms/bulma#962]
### Overview of the problem
 This is about the Bulma **CSS framework** 

I have used bulma since it's first released. It does the job done really nicely and really enjoy the declarative approach, makes reading html a breeze. 

### Proposal 

We should be able to extend bulma via npm. For example bulma does not provide plugin that includes javascript. We can create a standard or contract that will let us easily plug new functionality.

publish new plugins to npm with fixed naming convention will make it easier to find.

colors will let you change the color scheme

``` 
bulma-colors-default
bulma-colors-metarialui
```

plugins will include css or js extensions to add new feature.
```
bulma-plugin-{js}-dropdown
bulma-plugin-{vue}-datepicker
bulma-plugin-{react}-selectize 
```

_This is not a full formed idea. Just to start a conversation, how to have a sustainable modular approach for growth of bulma._

**Comment by VizuaaLOG** [comment]
There should maybe a 'base' library that others can extend. Maybe just a `Bulma` object with some helper methods like `addClass`, `removeClass` etc. Although due to Bulma's requirement on Flexbox `element.classList` may be supported on all browsers that support flexbox?

I was actually thinking about building a vanilla JS library for the Bulma components/elements that need some JS magic, like the mobile nav toggle and notifications.

What helper methods do you think would be useful in the base package, that other packages can then use?

We may also be able to implement an `extend` feature whereby you can add functionality to the Bulma base library so that you can do things like `this.addClass(elem, class)`?

So an idea of the API might be:

```javascript
// This is my-bulma-plugin.js
class Notification {
    constructor(myNotificationSelector) {
        // ....
    }
}

Bulma.extend('Notification', Notification);
```

An end user can then do something like the following:

```javascript
// app.js
// Bulma libs loaded
let notification = new Bulma.Notification('.notification');

// We can now interact with the notification object.
```

**Comment by VizuaaLOG** [comment]
Just a quick update on this. I have started to put together some JS plugins for Bulma components. [You find the project here](https://github.com/VizuaaLOG/BulmaJS). I'm always quickly implemting the JS functionality in projects, so thought I would have a crack at creating a JS plugin for all the components that would benefit from some JS magic.

Feedback and contributions are very welcome! This is a very early stage of development, so I wouldn't yet use these for production unless you like living dangerously!
