### ISSUE TITLE
[Docs] Bulma partners hero broken

### ISSUE THREAD

**Issue by VizuaaLOG** [jgthms/bulma#973]
### Overview of the problem

This is about the Bulma **Docs**

My **browser** is: Google Chrome 60

### Description
The Bulma partners section on the docs appears to be broken. This is the same on all pages.

[Imgur](http://i.imgur.com/173Pfzk.png)

### Steps to Reproduce

1. Visit one of the docs pages. I.e the [Box](http://bulma.io/documentation/elements/box/) documentation.
2. Scroll to the bottom of the page

### Expected behavior
The layout of the hero should be similar to the hero below it, with the content spanning the hero and not being a small centered column.

### Actual behavior
The text within the hero is squished, making it difficult to read.

**Comment by ivangreene** [comment]
I find this only happens with an Ad blocker enabled. Maybe try whitelisting bulma.io because they serve unobtrusive ads.

**Comment by VizuaaLOG** [comment]
Oh really, I'll do that. Didn't know there were any ads actually. Always support stuff that deserves my bandwidth ;).

**Comment by VizuaaLOG** [comment]
Yep you're right, that's fixed it.

**Comment by Glogo** [comment]
I do not have adblocker enabled for bulma.io and I have the same issue as @VizuaaLOG described.
It appears that this hero has unnecessary `columns` class instead of proper `hero-body` as described in docs

<img width="1214" alt="screen shot 2017-10-11 at 11 08 50" src="https://user-images.githubusercontent.com/1913799/31431882-3a647354-ae75-11e7-96ad-598428b8063c.png">

**Comment by Glogo** [comment]
According to [this web archive](https://web.archive.org/web/20170624075744/http://bulma.io/documentation/elements/delete/), there used to be list of partners / ads but it's no longer working (not even in incognito mode).

Found out the issue is related to [this code snippet](https://github.com/jgthms/bulma/blob/master/docs/_includes/bsa.html#L19-L27).

I often use these docs in "touch" view - side by side with my IDE. It's only a bit frustrating to see it wrap like this :). Should this section be removed?

**Comment by tuanphpvn** [comment]
@jgthms Please can you check this problem?
How to produce this problem? =>  When I set the width of chrome's window = 900px.

I found out that because container's width do not set for that window size. 
Please review #1231 fix.
